### ISSUE TITLE
Dismiss source-data-ratings panel on 'outer' click

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#1119]
When clicking outside the source data rating popup we should auto close.

Perahps use `vm.$onInit` to register window handler (and `$onDestroy` to remove)

![image](https://cloud.githubusercontent.com/assets/576829/20760867/12b8d6fa-b719-11e6-82ac-dc0e1ebe0170.png)

**Comment by kamransaleem** [comment]
@kamransaleem

**Comment by davidwatkins73** [comment]
Lets fix as part of section re-write otherwise lots of boilerplate duplication.
