### ISSUE TITLE
Migrate to angular-bootstrap 2.x

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#1277]
Although we should check to see how much we actually use.  Think it's just tabgroups  and popovers....

**Comment by davidwatkins73** [comment]
http://angular-ui.github.io/bootstrap/

**Comment by davidwatkins73** [comment]
~250k saving if we can move away from it.

**Comment by davidwatkins73** [comment]
Approx 20 usages of popovers
Approx 13 tabgroups

We have a solution for tabgroups (see `measurable-rating-app-section.html` / `_waltz-tabs.scss`)

Several simple popover libs exist: e.g. http://www.menucool.com/tooltip/css-tooltip

**Comment by kamransaleem** [comment]
Also the Dropdown for the navbar
Modal for login non SSO
Typeahead for search
