### ISSUE TITLE
Surveys Enhacement Request: Add checkbox/multi-select as an input type

### ISSUE THREAD

**Issue by paulellison** [finos/waltz#3192]
Add new checkbox form input type for surveys.

**Comment by kamransaleem** [comment]
Hi Paul,

Thanks for the suggestion, Waltz has the ability to pick a single value from an enumeration via a select dropdown in surveys.  Multi-value support is not currently supported, but has been requested by one of our clients. 

Are we correct in interpreting this request is for multi-value support?

**Comment by paulellison** [comment]
Hi Kamran,

Thanks for the quick response.  Yes, it would be correct to interpret this as requesting multi-value support although in some cases, checkboxes would make surveys easier to complete compared to say multi-select's in a drop down box.

**Comment by rovats** [comment]
We could support two options for multi-select:

* Multi Select - Dropdown
* Multi Select - Checkbox

Will probably need to store responses in a separate table:

**`survey_question_multi_select_response`** or **`survey_question_response_multi_select`**

```survey_instance_id | question_id | response```

Or we could potentially store the responses in the current table as a delimited string, but might be a bit difficult to manage.

**Comment by rovats** [comment]
@davidwatkins73 @kamransaleem @paulellison thoughts?
