### ISSUE TITLE
Build: Create Travis job for building against Postgres

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#3699]
Hopefully will be very similar to the existing (Maria) job

**Comment by rovats** [comment]
Might also be worth looking at automatically publishing incremental releases:
https://docs.travis-ci.com/user/deployment/releases/

**Comment by davidwatkins73** [comment]
y, looks like it's a bit of a pain in Travis to create multiple builds of the same thing with differing database backends.  May look around at some other CI offerings.
