### ISSUE TITLE
Build: Investigate AppVeyor for CI with SQLServer

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#3700]
https://www.appveyor.com/

**Comment by rovats** [comment]
+1 , will be good to have incremental builds to install on client dev environments

**Comment by davidwatkins73** [comment]
This could be tricky:

- AppVeyor doesn't seem to have much support for Java/Maven out of the box
- jOOQ license could be problematic.  Probably will need to investigate publishing from a private build server to avoid making the paid-for libs accessible to world
