### ISSUE TITLE
Export logical flow view to pdf

### ISSUE THREAD

**Issue by rovats** [finos/waltz#3727]
Example:
https://d3export.housegordon.org/
https://github.com/agordon/d3export_demo

* d3 -> SVG (browser)
* SVG -> PDF (server)

![image](https://user-images.githubusercontent.com/15289335/50631261-b68a2400-0f69-11e9-89b8-874f63464c28.png)

**Comment by davidwatkins73** [comment]
Note: We need to rework this view to be datatype hierarchy aware.

**Comment by rovats** [comment]
We could also look at converting SVG to PNG directly in the browser:
https://svgopen.org/2010/papers/62-From_SVG_to_Canvas_and_Back/index.html

**Comment by davidwatkins73** [comment]
Y, done that before. It was fairly simple. (If the viewbox has moved it becomes a bit trickier as you need to recenter)

**Comment by rovats** [comment]
Outputs using Apache Batik/FOP on the server (the icon fonts are missing, need to find a way to fix that):

JPEG:
![image](https://user-images.githubusercontent.com/15289335/50879146-e456e900-13ff-11e9-9f8d-cfa323c265ea.png)

PDF:
![image](https://user-images.githubusercontent.com/15289335/50879084-9b9f3000-13ff-11e9-85f5-2fb1d4300075.png)

**Comment by davidwatkins73** [comment]
Would this approach if some styling (color etc) were applied via external css ?

**Comment by rovats** [comment]
No, I don't think it would on the server.

**Comment by davidwatkins73** [comment]
We have added the ability to export diagrams to PNG.  Think this mostly covers this use case.
