### ISSUE TITLE
Database Information: migrate asset_code to Database Usage table

### ISSUE THREAD

**Issue by kamransaleem** [finos/waltz#3784]
Ensure that any dependent client entity statistics are modified accordingly.

| Column            | Type      | Mandatory | Description                  |
|:------------------|:----------|:----------|:-----------------------------|
| `database_id`     | long      | **y**     | id of database               |
| `entity_kind`     | long      | **y**     | the kind of the using entity |
| `entity_id`       | long      | **y**     | the id of the using entity   |
| `last_updated_by` | string    | **y**     | who updated this last        |
| `last_updated_at` | timestamp | **y**     | when this record was created |
| `provenance`      | string    | **y**     | the provenance of the record |

**Comment by davidwatkins73** [comment]
Dupe of #5395 ?
