### ISSUE TITLE
Rebuild measurable hierarchy after manual taxonomy edits

### ISSUE THREAD

**Issue by rovats** [finos/waltz#4147]
May be just rebuild the modified measurable category id?

**Comment by rovats** [comment]
The taxonomy edit feature is being used extensively by a client's team, and without this feature, their workflow is being hampered (eg: can't delete newly created nodes without a hierarchy rebuild, mapped apps not showing up).

**Comment by davidwatkins73** [comment]
Closely relates to #3710.  Will close that issue (not this)
