### ISSUE TITLE
Ratings panel: popover shows underlying Waltz logo

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#4790]
...suspect this is something to do with `append-to-body="true"` on the popover.

**Comment by davidwatkins73** [comment]
Can be seen even in embedded mode:  `embed/internal/MEASURABLE/44226/21`

**Comment by rovats** [comment]
@davidwatkins73 this has just been noticed here, I tried setting `append-to-body="false`, but that doesn't fix it. Any ideas?

**Comment by rovats** [comment]
Found the issue, happens because the popover template is in a separate file:
`uib-popover-template="'wric-rating-popup.html'"`

Moving the template code into `rating-indicator-cell.html` fixes the issue.

**Comment by davidwatkins73** [comment]
Ah, I moved that file out of the parent file because it _seems_ to cause
the template to be included repeatedly (inspect the page source).

Will also take a look.

**Comment by rovats** [comment]
@davidwatkins73 Yes, the template seems to be getting included multiple times. I tried various combinations of external template paths, but none of those seem to work.

I guess moving the template back inline is the potential stop gap solution, unless you know a way to resolve the external template?
