### ISSUE TITLE
MySql / MariaDB: cannot complete 1.23 scripts

### ISSUE THREAD

**Issue by kamransaleem** [finos/waltz#4795]
error as follows:
```
Cannot add a non-primary key identity column, db.changelog-1.23.xml::20200224-4712-3
```

**Comment by davidwatkins73** [comment]
I've double checked Postgres and it's fine

**Comment by kamransaleem** [comment]
thanks @davidwatkins73

**Comment by panterose** [comment]
as hint, I've fixed my mariadb install with:
```
<changeSet` id="20200224-4712-3"
               author="kamransaleem">
        <addColumn tableName="logical_flow_decorator">
            <column name="id"
                    type="${id.type}"
                    autoIncrement="true">
				<constraints nullable="false" primaryKey="true" unique="true"/>
            </column>
        </addColumn>
</changeSet>
```
and I removed 20200224-4712-4 as the primaryKey contraint is now included

**Comment by davidwatkins73** [comment]
@panterose : thanks for the fix.
@kamransaleem : should be easy to adapt the above, add filters to the existing step and add this one in for maria.  The subsequent step will need to be also filtered.

**Comment by kamransaleem** [comment]
@panterose Very helpful, thanks!
