### ISSUE TITLE
Error: Unable to access jarfile ../waltz-web/target/uber-waltz-web-1.0-SNAPSHOT.jar

### ISSUE THREAD

**Issue by jrutkin** [finos/waltz#4808]
Hi 

I have managed to get waltz to build successfully, however am having difficulty in actually getting it to run

the waltz/bin directory contains a run.sh file, however the build doesn't seem to create a jar per above.

I therefore get the error

Error: Unable to access jarfile ../waltz-web/target/uber-waltz-web-1.0-SNAPSHOT.jar

I have only the below in the waltz-web/target directory

waltz@waltz:~/waltz/waltz-web/target$ ls
classes		   generated-test-sources  surefire-reports  waltz-web		    waltz-web.war
generated-sources  maven-archiver	   test-classes      waltz-web-sources.jar

Thanks!

**Comment by kamransaleem** [comment]
Hi John, 

If you take the waltz-web.jar from the target directory you can deploy this directly to a tomcat server and it should run fine.  You will need to provide the database connection details via a .properties file however.

see example here: https://github.com/finos/waltz/blob/master/waltz-web/example.waltz.properties.md

A good place for the .properties file is in a directory named .waltz under your home directory.

Let me know how you get on with this...
Kamran
