### ISSUE TITLE
Asset Costs: Make YTD label configurable

### ISSUE THREAD

**Issue by rovats** [finos/waltz#4815]
If there are costs available for the current year, the YTD label is added automatically, which sometimes might not be desired (eg: if displaying projected costs for the current year).

So, this label should be made configurable based on a setting (similar to the default currency setting).

**Comment by davidwatkins73** [comment]
Is this something you are intending to pick up ?

**Comment by rovats** [comment]
@davidwatkins73 This has not been currently scheduled in a sprint here. 
Happy if someone else wants to pick this up.
