### ISSUE TITLE
Activating Waltz in FINOS Foundation

### ISSUE THREAD

**Issue by mcleo-d** [finos/waltz#4872]
### Description of Waltz Activation Criteria
Virtually all FINOS hosted projects are expected to strive towards, and ultimately attain, [Active  status](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530371/Active). 

This indicates to potential consumers that the project has reached a level of maturity, both functional and non-functional, that it is suitable for production use.

This epic has been created to present the activation requirements in the table below and to collect the materials needed to activate Waltz as an individual, or series of, linked issues.  

A full description of FINOS project activation is linked and found in the table below.
* https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530376/Activation

|  | **Activation (promotion to Active State)** | How and Where Demonstrated |
|:------ |:----------- |:----------- |
| **What it means for consumers?**   | The Project is high quality, mature from a codebase and community dynamics perspective. The Project produces valuable releases to solve a useful business problem for our Community. |  <ul><li>[x] [Open Milestones](https://github.com/finos/waltz/milestones)</li><li>[x] [Closed Releases](https://github.com/finos/waltz/milestones?state=closed)</li></ul> |
| **What it means for the Project Team?** | Glory in the Community<br/>Increased visibility and positioning in FINOS web resources, marketing and Community building efforts like meetups, blog posts, etc. |  <ul><li>[x] #4912 - Ready for Review</li></ul> |
|  | **QUALITY & SECURITY** |   |
| **Development Process** | <p>The Project adopts best-of-breed standards of distributed software development, including but not limited to:</p><ul><li>semantic versioning</li><li>tagging / branch protection</li><li>continuous integration ("CI") and continuous delivery ("CD") where applicable</li></ul><p>If Project Team choses not to use the FINOS provided Open Developer Platform (ODP), a comparable SDLC should be adopted and made available.</p> |  <ul><li>[x] #4913 - Ready for Review - Final item - https://github.com/finos/open-developer-platform/issues/148</li></ul> |
| **Build & Release** | <p>The Project code/documentation release process automated or at lest well documented.</p><p>If code is published, publicly redistributed release binaries should be listed or referred to in the documentation (e.g. under the FINOS namespace in an artefact repository or package manager, e.g. NPM, Maven Central, etc.)</p> |  <ul><li>[x] #4887 - Ready for Review</li></ul> |
| **Security** | <ul><li>No OWASP Top 10 warnings are present in the code</li><li>No long-standing medium or higher vulnerabilities (2+ months) and proper security disclosure processes</li><li>Any cryptographic functions and key lengths used within the software should be identified and vetted with Foundation's legal counsel in order to request compliance with U.S. Export policy.</li></ul> |  <ul><li>[x] [FINOS Contribution Validations](https://finosfoundation.atlassian.net/browse/CONTRIB-60)</li><li>[x] [Scheduled Integrated OWASP Security Scanning](https://github.com/finos/waltz/blob/dfd7c86712bd8d16c00ccb2eb930b9d3b9a0f005/pom.xml#L529)</li><li>[x] [OWASP Plugin Documentation](https://github.com/finos/waltz/blob/e6085dad5ca3d212edb05e23bede8b521657a052/docs/development/release-lifecycle.md)</li><li>[x] [Integrated Synk Vulnerability Scanning (example automated PR)](https://github.com/davidwatkins73/waltz-dev/pull/102)</li><li>[x] Cryptographic functions and key lengths not applicable</li></ul> |
| **Documentation** | <p>The README.md must include or reference up to date:</p><ul><li>end user docs, including a description of the software, feature overview, installation & configuration instructions</li><li>developer docs, including links to other external systems (further docs, wiki, CI & validation tools, artefact repository, change log / history, etc.)</li><li>where possible badges (e.g. from shields.io) are encouraged</li><li>sample code explaining how to use the project, library, standard, SDK, etc.</li></ul> |  <ul><li>[x] [README.md](https://github.com/finos/waltz/blob/master/README.md)</li><li>[x] [Waltz Microsite](https://waltz.finos.org/)</li><li>[x] [Project Docs](https://github.com/finos/waltz/tree/master/docs)</li><li>[x] [Features Docs](https://github.com/finos/waltz/blob/master/docs/features/README.md)</li><li>[x] [Development and Build Docs](https://github.com/finos/waltz/tree/master/docs/development)</li></ul> |
|  | **DIVERSITY & VIABILITY** |       |
| **Community** | Project has active participation from 2+ independent individuals and/or organizations; Ideally Project Team members who make contributions in connection with their employment are doing do as part of their regular job duties. |  <ul><li>[x] Contributions to Waltz from Deutsche Bank, NatWest Markets and Individuals </li><li>[x] [Waltz Contributor Graphs](https://github.com/finos/waltz/graphs/contributors)</li></ul> |
| **Project Team** | Project Team has/have demonstrated active involvement in PMC and have demonstrated commitment to furthering overall Program goals |  <ul><li>[x] No longer required</li></ul> |
| **License** | Project must not have dependencies which effectively restrict how the project may be distributed or deployed and must not depend on any proprietary third-party components for their core functionality. |  <ul><li>[x] Waltz distributed under [Apache 2 License](https://github.com/finos/waltz/blob/1.25.1/license.txt)</li><li>[x] [Licensing pre-contribution checks](https://finosfoundation.atlassian.net/browse/CONTRIB-61) conducted by @maoo from FINOS</li></ul> |
| **Trademark** | Community is using a different established Project name or original contribution trademark is owned by FINOS. All Project related websites and assets are owned and hosted by FINOS. |  <ul><li>[x] https://waltz.finos.org/</li></ul> |
|  | **ROADMAP & RESOURCES** |       |
| **Progress** | Project has progressed against its public roadmap during incubation; roadmap is aligned with, and where applicable incorporated into, the overall program roadmap or backlog |  <ul><li>[x] Latest Waltz release is [v1.25.1, June 18 2020](https://github.com/finos/waltz/releases/tag/1.25.1) against product [roadmap](https://github.com/finos/waltz/blob/master/docs/features/roadmaps/README.md)</li></ul> |
| **Versioning** | Project software is production grade and ready for large scale consumption. 1.0.0 version was released and announced it to the announce@ mailing list. |  <ul><li>[x] Waltz was announced to FINOS community upon contribution</li><li>[x] Latest Waltz release is [v1.25.1, June 18 2020](https://github.com/finos/waltz/releases/tag/1.25.1) against product [roadmap](https://github.com/finos/waltz/blob/master/docs/features/roadmaps/README.md)</li></ul> |
| **Roadmap** | Projects share and work to a public roadmap, aligned with the overall program roadmap. |  <ul><li>[x] FINOS Program alignment not required</li><li>[x] [Roadmaps and Scenarios](https://github.com/finos/waltz/blob/master/docs/features/roadmaps/README.md) documented in [features folder](https://github.com/finos/waltz/tree/master/docs/features)</li></ul> |
| **FINOS Support** | Project Team is largely self-sufficient, requiring minimal operational support from FINOS to govern the maintain the project. FINOS support switches to strategic growth of the Project in the Community. |  <ul><li>[x] [The team operate independently through Issues](https://github.com/finos/waltz/issues)</li><li>[x] [The team operate independently through Milestones](https://github.com/finos/waltz/milestones)</li><li>[x] The team engage with FINOS as and when required</li></ul> |
|  | **GROWTH & ADOPTION** |       |
| **Usefulness** | The Project demonstrably solves a real life use case in the Community. Evidence of adoption beyond the contributing individuals or firms (e.g., in the form of download statistics, listing known deployments or implementations, etc.) |  <ul><li>[x] #4802 demonstrates team commitment to make installing Waltz easier with Docker</li><li>[x] https://github.com/rovats/waltz-docker by @rovats demonstrates commitment to making developer environment easier with Docker</li><li>[x] [natwestmarkets](https://github.com/natwestmarkets/waltz)</li><li>[x] [Diffblue](https://github.com/Diffblue-benchmarks/waltz)</li><li>[x] [AlgoSkyNet](https://github.com/AlgoSkyNet/waltz)</li><li>[x] [commbankoss](https://github.com/commbankoss/waltz)</li></ul> |
| **Status Badging** | Project Team commits to adopt the FINOS Active badge in the README.md once PMC approves activation properly signal adopters the new state of the Project |  <ul><li>[x] @davidwatkins73 confirms FINOS Active badge can be added to Waltz README.MD</li></ul> |
|  | **HYGIENE & OPERATIONS** |       |
| **Compliance** | The appropriate license text is included in each source file's header. See details and template |  <ul><li>[x] [License File](https://github.com/finos/waltz/blob/master/license.txt)</li><li>[x] [Notice File](https://github.com/finos/waltz/blob/master/NOTICE.md)</li><li>[x] [Contributing File](https://github.com/mcleo-d/waltz/blob/master/.github/CONTRIBUTING.md)</li><li>[x] [Code of Conduct File](https://github.com/mcleo-d/waltz/blob/master/.github/CODE_OF_CONDUCT.md)</li></ul> |
| **Community Inquiries** | Community inquiries on the project channels (mailing lists, issues and pull requests, etc) are generally promptly answered |  <ul><li>[x] [Demonstrated through Open Issues](https://github.com/finos/waltz/issues)</li><li>[x] [Demonstrated through Closed Issues](https://github.com/finos/waltz/issues?q=is%3Aissue+is%3Aclosed)</li><li>[x] [Demonstrated through Closed PRs](https://github.com/finos/waltz/pulls?q=is%3Apr+is%3Aclosed)</li></ul> |
| **Meeting Hygiene** | If the project meets regularly on-line, the Project Team has demonstrated a track record of publishing and distributing agenda no less than 24 hours before the meeting, and publishes meeting minutes after calls. |  <ul><li>[x] [Comms demonstrated through Issues](https://github.com/finos/waltz/issues)</li><li>[x] [Work prioritised through Milestones](https://github.com/finos/waltz/milestones)</li></ul> |
| **Transparency** | Project Team has adopted a transparent governance model(*) consistent with FINOS Community governance. Work for new contributors is organized into issues within a public issue tracking system, as appropriate, tagged as "Good First Issues" |  <ul><li>[x] [Labels Demonstrated on Waltz](https://github.com/finos/waltz/labels) </li><li>[x] [_'Good First Issue'_ Available for project use](https://github.com/finos/waltz/labels/good%20first%20issue)</li></ul> |

_(*) transparent governance model is when a project’s discussions, minutes, deliberations, project plans, issue tracking plans for new features, and other artefacts are open, public, and easily accessible in the FINOS Project Infrastructure or FINOS sanctioned external system._

**Comment by mcleo-d** [comment]
Hi @davidwatkins73 👋 

It'll be great to schedule a call to start breaking this epic into the stories that are complete and can be demonstrated now ... and then ... the stories we need to complete to deliver the epic this quarter.

Let me know your thoughts on dates and times.

James.

**Comment by davidwatkins73** [comment]
How about tomorrow afternoon ? Free most of the time.

**Comment by mcleo-d** [comment]
@davidwatkins73 and @maoo - I have tagged you both in the **Security** section of the activation criteria to confirm everything in this area is expected. Please check the box in this section when you're both happy this criteria has been met 👍

**Comment by mcleo-d** [comment]
@mcleo-d to add #4802 to activation story.

**Comment by mcleo-d** [comment]
@mindthegab and @maoo - Waltz's Activation in FINOS is now **Ready for Review** by the FINOS team. Please feel free to feedback to @davidwatkins73 and @mcleo-d 👍

**Comment by mindthegab** [comment]
@davidwatkins73 and @mcleo-d - thank you so much for such a thorough documentation and review of our lifecycle. /cc @brooklynrob @toshaellison and @maoo as this is an amazing example of a well documented activation.

I am happy to confirm Waltz is ready to become an active project (and we will announce it our next marketing cycle /cc @grizzwolf). 

Simply merge #4990 to get the badge and contextually close this issue.

Congratulations!
