### ISSUE TITLE
Homepage improvements

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#4876]
The Waltz homepage is largely static and uninteresting to users after their first viewing.
This issue is an analysis task to see what dynamic elements could/should be included on the homepage to increase user engagement and to help users understand what recent changes in the Waltz dataset may effect them.

**Related:**
#4609

Possible work items:

- Backend
  - [x] SQL for summarizing changelogs (all changes for apps mentioned in a _group_ )  - JWS : 1  
        - not just app groups!
        - summarization by date (raw counts) for heatmap  
        - summarization by app and child entity kind for table view, focused on selected heatmap date
  - [x] DDL add `is_favourite` column to `application_group` (plus prov , plus is_readonly)  - DW : 1
- Services
  - [x] create favourite service which can 'add / remove' applications - JWS:2 
     - how do we stop removal of 'direct apps'  ?  
        - possibly add an `is_readonly` column to `app_group_*_entry`
        - maybe also add provenance to `app_group_*_entry` to simplify recreation
     - needs to create favourite group if none exists
   - [x] service to expose summarization - DW : 2
   - [x] limits should be based on number of days, not record-counts
- Frontend
  - [x] add favourite button (bookmark / bookmark-o or star/star-o) which calls service
  - [x] distinguish read-only items (i.e. greyed out bookmark/half-star)
  - [x] notification on add/remove
  - [x] add scroll region to app groups  (small change)
  - [x] create heatmap (i.e. steal/adapt d3 examples - search `d3 calendar heatmap`) - DW/JWS : 3
  - [x] _heatmap on-click_ shows breakdown table for that date
  - [x] create attestation/survey mini section (so it's not hidden in the profile menu)
  - [x] re-layout homepage, with an explicit news section.
  - [x] browser detect and banner recommending chrome etc.  Wording should be from database so that links to internal software repos can be specified.

**Comment by davidwatkins73** [comment]
Possible work items:

- [ ] foo 
- [ ] baa

**Comment by davidwatkins73** [comment]
![image](https://user-images.githubusercontent.com/576829/86132016-4288f780-bade-11ea-84b6-2d3be68f66d9.png)

**Comment by davidwatkins73** [comment]
![image](https://user-images.githubusercontent.com/576829/86286654-c4f8e080-bbde-11ea-91a4-a70313d410af.png)

- List is now in a scrollable region which is searchable.
- The operations: _unsubscribe_ and  _delete_ are now immediately available
- panel switches to a search mode when looking for shared public groups (see below)

![image](https://user-images.githubusercontent.com/576829/86286963-510b0800-bbdf-11ea-849d-6d7ac330d5e2.png)

**Comment by MarkGuerriero** [comment]
Like the look of the app group scroller -this will make it a lot easier to manage the list and also free up screen real estate.

**Comment by davidwatkins73** [comment]
Illustrative code change for bookmark widget support:

[demo_of_transclude_to_do_actions.patch.txt](https://github.com/finos/waltz/files/4870444/demo_of_transclude_to_do_actions.patch.txt)

**Comment by davidwatkins73** [comment]
Demoing @JWoodland-Scott 's work.  Adding and removing favourites and then seeing them in the (newly created) personal favourites group:

![add_remove_favourite](https://user-images.githubusercontent.com/576829/86965654-caff3c00-c15f-11ea-8fb5-3d360e3fb8d6.gif)

**Comment by davidwatkins73** [comment]
Attestation / Survey widget to show outstanding counts.


![image](https://user-images.githubusercontent.com/576829/87324506-13d03f80-c528-11ea-9f6d-5c78b2f2ccf9.png)

**Comment by davidwatkins73** [comment]
![change-log-homepage-drill-down](https://user-images.githubusercontent.com/576829/87990679-65566c80-cadc-11ea-9b2f-77a6447a0bd0.gif)

@MarkGuerriero
