### ISSUE TITLE
FINOS Activation: Build and Release: document version numbering

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#4887]
#4872

**Comment by mcleo-d** [comment]
### Description
This issue relates to the **Build & Release** section of the FINOS activation criteria which is described below ..

### Activation Criteria
- [ ] The Project code/documentation release process automated or at lest well documented.
- [ ] If code is published, publicly redistributed release binaries should be listed or referred to in the documentation (e.g. under the FINOS namespace in an artefact repository or package manager, e.g. NPM, Maven Central, etc.)

**Comment by mcleo-d** [comment]
@davidwatkins73 - I have added the success criteria of this item to the comments so it's easily referenced in this issue 👍

**Comment by mcleo-d** [comment]
@davidwatkins73 - This story is now ready for review by FINOS 👍
