### ISSUE TITLE
Waltz website summary displaying incorrect meta description content

### ISSUE THREAD

**Issue by mcleo-d** [finos/waltz#4889]
### Description
When sharing https://waltz.finos.org/ on Slack, the description of the site reads `A layout example that shows off a responsive product landing page` as the meta description. 

_See screenshot below_

![waltz-1](https://user-images.githubusercontent.com/6029572/82684227-23c75380-9c4a-11ea-9e5e-df3d0df4f0f8.png)

### Potential Fix
Change the page `meta` `description` `content` reflected below to something more appropriate for Waltz. 

`<meta name="description" content="A layout example that shows off a responsive product landing page.">`

_For example_

`<meta name="description" content="Waltz - Enterprise architecture on the wire">`

**Comment by davidwatkins73** [comment]
Hi James, thanks for writing this up.  I've made the change on the docs branch, tested it and pushed the change.
