### ISSUE TITLE
Increased visibility and positioning in FINOS web resources, marketing and Community building efforts like meetups, blog posts, etc.

### ISSUE THREAD

**Issue by mcleo-d** [finos/waltz#4912]
### Description
This activation story contains references that relate to building **Increased visibility and positioning in FINOS web resources, marketing and Community building efforts like meetups, blog posts, etc.**

### Initiatives Done
- [x] Waltz Microsite - https://waltz.finos.org/
- [x] [Introduction to FINOS Waltz](https://www.finos.org/blog/introduction-to-finos-waltz) blog on FINOS website
  - https://www.finos.org/blog/introduction-to-finos-waltz 
- [x] NatWest Markets Internal Brown Bag Session - Wed 27th May 2020
  - https://github.com/davidwatkins73/prezzos/tree/master/brownbag-202005
- [x] FINOS Community All Hands - Thursday 11th June 2020
- [x] Waltz Screencasts and Documentation was created and published on Waltz microsite
  - [Screencast: Developers - Schema Modifications](https://waltz.finos.org/blog/waltz/dev/screencast/2020/06/25/dev-schema-modifications.html)
  - [Screencast: Installing a Waltz demo instance](https://waltz.finos.org/blog/waltz/admin/screencast/2020/06/25/run-docker-demo.html)
  - [Screencast: Developers - UI Sections](https://waltz.finos.org/blog/waltz/dev/screencast/2020/06/18/dev-ui-sections.html)
  - [Screencast: Developers - Getting Started](https://waltz.finos.org/blog/waltz/dev/2020/06/18/dev-getting-started.html)
  - [Formalising code architecture using ArchUnit](https://waltz.finos.org/blog/waltz/dev/2019/01/20/arch-unit.html)
- [x] FINOS Virtual Meetup and Podcast - **Introducing Waltz** - Wed 12th August 2020 @ 4pm BST
  - [x] @davidwatkins73 to confirm meetup and podcast date and time
  - What is Waltz?
  - What business/IT challenges does it solve?
  - Who is using it already?
  - How do you consume?
  - How do you contribute?

**Comment by mcleo-d** [comment]
@davidwatkins73 - I've started logging all the Waltz related community activities in this issue. Feel free to add to the list or make notes in the comments 👍 

Also, please let me know if you're okay presenting Waltz at a FINOS Virtual Meetup and Podcast on Wed 24th June 2020 @ 4pm BST? 😄

**Comment by davidwatkins73** [comment]
Linking to [presentation given to NWM](https://github.com/davidwatkins73/prezzos/tree/master/brownbag-202005)

**Comment by mcleo-d** [comment]
@davidwatkins73 - I have added activities done to date and marked this story ready for review by the FINOS team 👍

**Comment by mindthegab** [comment]
@davidwatkins73 and @mcleo-d - thank you so much for such a thorough documentation and review of our lifecycle. /cc @brooklynrob @toshaellison and @maoo as this is an amazing example of a well documented activation.

I am happy to confirm Waltz is ready to become an active project (and we will announce it our next marketing cycle /cc @grizzwolf). 

Simply merge #4990 to get the badge and contextually close this issue.

Congratulations!
