### ISSUE TITLE
The Project adopts best-of-breed standards of distributed software development

### ISSUE THREAD

**Issue by mcleo-d** [finos/waltz#4913]
### Description
The Project adopts best-of-breed standards of distributed software development, including but not limited to:

* semantic versioning (if appropriate)
* tagging / branch protection
* continuous integration ("CI") and continuous delivery ("CD") where applicable

If Project Team choses not to use the FINOS provided [Open Developer Platform (ODP)](https://www.finos.org/open-developer-platform), a comparable SDLC should be adopted and made available.

### Success Criteria
- [x] An indication of how Waltz adopts best-of-breed standards of distributed software development is given in https://github.com/finos/waltz/issues/4913#issuecomment-644646530
  - Providing links to documentation that explains the software engineering standards and methods.
  - Providing links to code in the Waltz repository that demonstrates the standards and methods being applied. 
  - Describing the methods in the comments below this issue.

**Comment by davidwatkins73** [comment]
- Versioning information has been documented in PR #4946 
- The [versioning document](https://github.com/finos/waltz/blob/master/docs/development/release-lifecycle.md) describes common 'hygiene' tasks for each release
- The [issues](https://github.com/finos/waltz/blob/master/docs/development/issue_management/issue_management.md) document describes issue lifecycle and common tags
- Unable to check branch protection, looks like this permission was lost during the xfer of Waltz to FINOS
- CI is currently done by [Travis](https://travis-ci.org/github/finos/waltz) on all pure open source variants (i.e. **not** MSSQL)

**Comment by mcleo-d** [comment]
@davidwatkins73 - I have opened the following issue https://github.com/finos/open-developer-platform/issues/148 to check Waltz project permissions with @maoo regarding the following comment ...

* '_Unable to check branch protection, looks like this permission was lost during the xfer of Waltz to FINOS_'

**Comment by mcleo-d** [comment]
@davidwatkins73 - I have updated your bullets to checkboxes on https://github.com/finos/waltz/issues/4913#issuecomment-644646530

We can mark this story as Ready for Review when @maoo has checked your permissions and branch protection 👍

**Comment by mcleo-d** [comment]
@davidwatkins73 - I have marked ready for review for the FINOS team and will work with @maoo on the branch protection issue 👍

**Comment by davidwatkins73** [comment]
Thats awesome.  Thanks so much for all the work you've put into this !

**Comment by mcleo-d** [comment]
> Thats awesome. Thanks so much for all the work you've put into this !

It's my absolute pleasure @davidwatkins73 :)

**Comment by mcleo-d** [comment]
@davidwatkins73 - The branch protection has been completed by @maoo. 

It would be great if you could test according to https://github.com/finos/open-developer-platform/issues/148#issuecomment-655626164 so I can close the ODP issue.

Thanks!
