### ISSUE TITLE
Review and transition of Waltz team into FINOS Organisation Teams

### ISSUE THREAD

**Issue by mcleo-d** [finos/waltz#4921]
### Description
The issue ensures the Waltz team are correctly represented in [FINOS Organisation Teams](https://github.com/orgs/finos/teams) with expected permissions applied.

### Acceptance Criteria
- [x] Waltz team are represented in [FINOS Organisation Teams](https://github.com/orgs/finos/teams).
- [x] Waltz team has been successfully transitioned from Waltz repo into Waltz FINOS Team.
- [x] Working with @davidwatkins73, the team have been given correct project permissions.
- [ ] Waltz project permissions have been successfully tested by @maoo and @davidwatkins73.

**Comment by mcleo-d** [comment]
@maoo and @davidwatkins73 - I've created this issue to ensure the Waltz team are represented in the [FINOS Organisation Teams](https://github.com/orgs/finos/teams). Please prioritise this issue together as it's likely to need a little collaboration.

**Comment by maoo** [comment]
Thanks @mcleo-d !

I've just invited @rovats to https://github.com/orgs/finos/people (TY for accepting the invitation so quickly)

For all new GitHub FINOS org members, make sure to mark as Public your affiliation with finos, by:
1. visiting https://github.com/orgs/finos/people
2. finding your user
3. switching affiliation from private to public

@davidwatkins73 - can you please confirm this is the right team composition?

<img width="440" alt="Screenshot 2020-06-03 at 13 16 43" src="https://user-images.githubusercontent.com/327285/83630678-84d11e80-a59c-11ea-9b43-960800929fd0.png">

If that's the case, feel free to close the issue, all settings have been updated already on our side. TY!

**Comment by mcleo-d** [comment]
Thanks for the fast response @maoo 👍 😁

**Comment by davidwatkins73** [comment]
Hi, yes this is the correct list.  

----

@muzammil-ali1 @kamransaleem @rovats @JWoodland-Scott @MarkGuerriero 

Could you update your affiliation to be public as described by @maoo above ?

Here's a screenshot of what you should see:
![image](https://user-images.githubusercontent.com/576829/84748905-2d29ae80-afb1-11ea-83cd-ecd3ce911783.png)

**Comment by maoo** [comment]
@davidwatkins73 - I just reviewed the team composition and it's correct, well done!

<img width="742" alt="Screenshot 2020-06-16 at 18 27 43" src="https://user-images.githubusercontent.com/327285/84801156-1d38bb80-afff-11ea-8114-38bc8c1031d7.png">

Let's keep the issue open until everyone in the team have switched their affiliation to public (assuming they're willing to of course).

**Comment by rovats** [comment]
@maoo Thanks for the invite earlier, I had switched my affiliation public soon after accepting the invite.

**Comment by maoo** [comment]
Configuration is good AFAICS. Below the list of project maintainers (those who can merge someone else's PRs).

@davidwatkins73 @mcleo-d  - feel free to close this issue if the team definition is correct. TY!

<img width="994" alt="Screenshot 2020-07-14 at 14 30 04" src="https://user-images.githubusercontent.com/327285/87425874-acc19200-c5de-11ea-8b9e-12ae40c15e17.png">

**Comment by davidwatkins73** [comment]
Looks good.  Thanks for the help.
