### ISSUE TITLE
Flow Diagram page: add entity named notes

### ISSUE THREAD

**Issue by rovats** [finos/waltz#4935]
At NWM, we auto generate flow diagrams for impact analysis, and there is a requirement display notes on Flow Diagrams for additional data (eg: impact statements etc).

**Comment by kamransaleem** [comment]
would these appear on the diagram itself or on the flow diagram page in a section?

**Comment by rovats** [comment]
Flow diagram page, in a section. Just need to add an entry in `dynamic-section-definitions.js`

**Comment by kamransaleem** [comment]
you ok to take this one?

**Comment by rovats** [comment]
Yep, I'll take it up, unless someone else wants it.

**Comment by davidwatkins73** [comment]
Making of:  https://youtu.be/-wiZK3jOZ2E  :)
