### ISSUE TITLE
Logos: add all Waltz logos to repo

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#4947]

**Comment by davidwatkins73** [comment]
@mcleo-d The files are now [in the repo](https://github.com/finos/waltz/tree/master/waltz-ng/images/branding/svg).

Alternatively you can download them directly from this attachment: 
[waltz-logos-svg.zip](https://github.com/finos/waltz/files/4787923/waltz-logos-svg.zip)

**Comment by mcleo-d** [comment]
Thanks @davidwatkins73 😀
