### ISSUE TITLE
Measurable Rating Decomms: date should not be set later than app retirement date

### ISSUE THREAD

**Issue by JWoodland-Scott** [finos/waltz#4968]

**Comment by davidwatkins73** [comment]
Will this be discouraged or disallowed?

**Comment by JWoodland-Scott** [comment]
Was thinking disallowed, if an app has set a planned retirement how could the planned rating decom be later? Also thinking for removed apps shouldn't be able to set a decom date?

**Comment by davidwatkins73** [comment]
ok, we would still need to cater for the scenario where the overall decomm date moves forward after the appFn decom date was given  (maybe the "hand/pointy" icon changes colour and the hover/selected description gives explicit details).

**Comment by JWoodland-Scott** [comment]
Ok, do you mean a scenario where the original app planned retirement date is updated to a later date after a decom date has been set, or where the planned app retirement date has been passed and the app is still active?

**Comment by davidwatkins73** [comment]
I was specifically thinking of this scenario (though others exist)  - Tx is the date of the record updates 

- T1  - App has existing retirement date of 2025
- T2 - AppFn retirement is set to 2024  (ok!)
- T3 - App retirement date brought forward to 2023  
  - at this point the gui should be indicating the data is inconsistent

Similar scenario exists when an app initially has no overall retirement date specified.

**Comment by rovats** [comment]
I think it should be discouraged, but not blocked. 
I have seen plenty of instances where apps are live beyond their planned retirement date, and the new retirement dates haven't been set yet.

**Comment by JWoodland-Scott** [comment]
Ah yes, understood! I was thinking maybe a waltz-warning once a measurable was selected but will look at updating the icons/hover too, could make the hand go amber or red, would definitely be more obvious at a glance!

**Comment by JWoodland-Scott** [comment]
Ah ok... shouldn't we ask for the planned app retirement to be updated in that case, if it's known that a function will be using up to a certain date... or possibly could allow future decom dates to be set again if the planned date has been passed?

**Comment by davidwatkins73** [comment]
Not entirely sure which dates you were talking about (app vs appFn) .....

Currently (in DB) the planned app retirement date is given to us, it's not something we control so we can't allow users to update it  (though ideally Waltz _should_ support this).

Problematic cases include:

- (as discussed above) appFn decom date is after the app decom date
- (what I think you were referring to) appFn decom date has passed and appFn is still 'active'

**Comment by JWoodland-Scott** [comment]
Ok, just to clarify then, should I be making this discouraged now instead of disallowed?

**Comment by davidwatkins73** [comment]
I am still of the opinion that this should be an advisory/discouraged feature, rather than being disallowed (or worse, auto-corrected)

Related: We should perhaps add a 'cleanup task' section on apps for things we know are wrong.
