### ISSUE TITLE
Flow decorators: interaction between logical flow datatypes and physical spec datatypes

### ISSUE THREAD

**Issue by JWoodland-Scott** [finos/waltz#5085]
Design doc to outline changes.

**Comment by davidwatkins73** [comment]
Perhaps a `nodeOptions` or similar object like: 
```
 return {
                    id: d.id,
                    parentId: d.parentId,
                    name: d.name, // just to get ordering working as multi-select tree assumes name is present
                    dataType: d,  // {....}
                    nodeOptions: {
                        isSelected: true,
                        isReadOnly: true,
                        isConcrete: d.concrete,
                        isSuggested: true,
                        isSuspicious: true,
                        confirmation: {
                            required: true,
                            message: ""
                        }
                    }
                }
```

**Comment by JWoodland-Scott** [comment]
How about something like:

select lf.id as 'lf id',
       ps.id as 'ps id',
       dt.id as 'dt id',
       dt.name,
       dt.deprecated,
       dt.concrete,
       lfd.is_readonly as 'lfd read-only',
       psdt.is_readonly as 'spec dt read-only',
       case when count(psdt2.specification_id) > 0 then 'true' else 'false' end as 'other specs',
       (select count(*) from physical_flow pfc where pfc.specification_id = ps.id) as 'count pf flows'
from physical_specification ps
inner join physical_spec_data_type psdt on ps.id = psdt.specification_id
inner join physical_flow pf on ps.id = pf.specification_id
inner join logical_flow lf on pf.logical_flow_id = lf.id
inner join logical_flow_decorator lfd on lf.id = lfd.logical_flow_id and lfd.decorator_entity_kind = 'DATA_TYPE'
inner join data_type dt on psdt.data_type_id = dt.id
left join physical_flow pf2 on lf.id = pf2.logical_flow_id and pf2.is_removed = 0 and pf2.id != pf.id
left join physical_specification ps2 on pf2.specification_id = ps2.id and ps2.is_removed = 0
                                            and ps.id != ps2.id
left join physical_spec_data_type psdt2 on ps2.id = psdt2.specification_id
                                             and dt.id = psdt2.data_type_id
where ps.id = xxxxxx
group by lf.id, ps.id, dt.id, dt.name, dt.deprecated, dt.concrete, psdt.is_readonly, lfd.is_readonly
order by lf.id

**Comment by JWoodland-Scott** [comment]
Possible 2nd step for returning allowable changes to logicals: 

```
select distinct ps.id as 'ps id',
       lf.id as 'lf id',
       dt.id as 'dt id',
       dt.name,
       psdt.is_readonly as 'spec dt read-only',
       lfd.is_readonly as 'lfd read only',
       case when count(psdt2.specification_id) > 0  then 'true' else 'false' end as 'underlying specs sharing dt',
       case when count(psdt2.specification_id) > 0 or lfd.is_readonly = 1 then 'true' else 'false' end as 'logical cannot be removed',
       (select count(*) from physical_flow pfc where pfc.specification_id = ps.id) as 'count pf flows',
       case when (lfd.decorator_entity_id is null) then 'true' else 'false' end as 'missing decorator aka "suspicious'
from physical_specification ps
       inner join physical_spec_data_type psdt on ps.id = psdt.specification_id
       inner join physical_flow pf on ps.id = pf.specification_id
       inner join logical_flow lf on pf.logical_flow_id = lf.id
       left join logical_flow_decorator lfd on lf.id = lfd.logical_flow_id and lfd.decorator_entity_kind = 'DATA_TYPE'
                                                  and lfd.decorator_entity_id = psdt.data_type_id
       inner join data_type dt on psdt.data_type_id = dt.id
       left join physical_flow pf2 on lf.id = pf2.logical_flow_id and pf2.is_removed = 0 and pf2.id != pf.id
       left join physical_specification ps2 on pf2.specification_id = ps2.id and ps2.is_removed = 0
  and ps.id != ps2.id
       left join physical_spec_data_type psdt2 on ps2.id = psdt2.specification_id
  and dt.id = psdt2.data_type_id
where ps.id = 92703
group by ps.id, dt.id, dt.name, dt.deprecated, dt.concrete, psdt.is_readonly, lf.id, lfd.is_readonly, lfd.decorator_entity_id
```
