### ISSUE TITLE
Minor UI Annoyances

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#5123]
Good first starter issues:

- [x] List of rating schemes on admin page is unordered
  - [x] bonus points for searcahable
- [x] Popover on mearuable rating value shows even if no hover help available

![image](https://user-images.githubusercontent.com/576829/95726570-ff0f5f00-0c70-11eb-812c-eea1e96baa57.png)

Note the popover behaviour sometimes works correctly.  Suspect it's related to empty/null strings.

**Comment by gharote88** [comment]
- [X]  List of rating schemes on admin page is ordered
   - [X] bonus points for searchable
- [X] Popover on measurable rating value shows even if no hover help available
