### ISSUE TITLE
Search Application by Asset-code/External identifier giving duplicate results

### ISSUE THREAD

**Issue by NWM-OS** [finos/waltz#5140]
If we have multiple external identifier for an application, the below link gives duplicate records.

${Waltz-url}/waltz/application/asset-code/CI024985

Issue is with ApplicationDao.findByAssetCode(String externalId) doing select instead of selectDistinct

**Comment by davidwatkins73** [comment]
Thanks for the bug report.  We'll get it fixed for the next release (1.29) currently pencilled in for mid/late Nov.
