### ISSUE TITLE
Server Page : More attributes on server overview block

### ISSUE THREAD

**Issue by NWM-OS** [finos/waltz#5152]
waltz-entity-enum block is available on other pages for showing extra attributes on overview panel

**Comment by davidwatkins73** [comment]
Updated the server information page to include the `waltz-entity-enum` tag.



Allows for new attrs to be introduced:

**Definition**
![image](https://user-images.githubusercontent.com/576829/99151326-43d44e80-2692-11eb-9966-623d9b6ebec4.png)

**Enum Options**
![image](https://user-images.githubusercontent.com/576829/99151371-9a418d00-2692-11eb-8918-362e6e47863c.png)

**Values** 
![image](https://user-images.githubusercontent.com/576829/99151396-c0ffc380-2692-11eb-8825-e778c6183f33.png)


**UI**

![image](https://user-images.githubusercontent.com/576829/99151285-e6d89880-2691-11eb-8bcf-7e0fa55f1c07.png)
