### ISSUE TITLE
Report Grid: add unique index on report grid col def

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#5296]
Currently allows duplicates rows.
Uniqueness should be on:   `report_grid_id, column_entity_kind, column_entity_id`

**Comment by davidwatkins73** [comment]
If toy are unsure about how to make schema modifications in Waltz this [video](https://www.youtube.com/watch?v=rIAJd-Ko8YA) takes you through the process.

**Comment by mcleo-d** [comment]
@MarkGuerriero and @davidwatkins73,

Can this issue be closed as whilst looking at `Good First Issues` I noticed the milestone linked to this issue is `done`? 

Another potential issue off the backlog! 🚀 

James

**Comment by JWoodland-Scott** [comment]
Hi James, 
We tend to leave them open until after the release, just marked with a label 'fixed(test & close)', we also update to the 'done' milestone. One the release has been issues we'll move everything in 'done'  to 'closed'.

Hope this makes sense !
More details [here](https://github.com/finos/waltz/blob/master/docs/development/issue_management/issue_management.md)
