### ISSUE TITLE
Search: Show external id in search results

### ISSUE THREAD

**Issue by kamransaleem** [finos/waltz#5555]
Will make it easier to distinguish where search results have the same

**Comment by kamransaleem** [comment]
<img width="377" alt="Waltz__Ad_hoc_32" src="https://user-images.githubusercontent.com/3029467/127468374-1de329c5-23b2-4ffd-bf73-f911a00960da.png">

**Comment by davidwatkins73** [comment]
Tried it with extremely long names / extIds and it looks fine:

![image](https://user-images.githubusercontent.com/576829/127528599-2a78b003-fc8a-4d2a-91ae-00a6fc2fc4b0.png)

**Comment by davidwatkins73** [comment]
Looks good, we should probably give serious consideration to `entityReference` becoming a base class/immutable for all entities.  Lots of overlap.....

**Comment by kamransaleem** [comment]
> Looks good, we should probably give serious consideration to `entityReference` becoming a base class/immutable for all entities. Lots of overlap.....

Would take one step out of the conversion.

**Comment by davidwatkins73** [comment]
...or perhaps a dedicated `EntitySearchResult` object which would be more flexible and prevents growth of `EntityReference`.
