### ISSUE TITLE
Waltz SVG size limit

### ISSUE THREAD

**Issue by strangetobefree** [finos/waltz#5772]
We are having an issue with the svg diagram size limit. it appears to be fairly small at 64kb. I have had a DBA investigating and I think the issue is in the application layer. would it be possible to raise this to 128kb? still fairly small, but crucially enough for a more detailed diagram to be displayed.

**Comment by davidwatkins73** [comment]
Will take a look at doing this for the upcoming release (1.39 - due late Nov)

Out of interest are you on sqlserver, postgres or maria ?

**Comment by davidwatkins73** [comment]
I've just tried this on a 136kb file with postgres and it seemed fine:
![image](https://user-images.githubusercontent.com/576829/142035028-45a65b66-9b5e-420c-82e9-a2167658883a.png)

The file I used is attached (took the ubiquitous svg tiger example and doubled it - you'll need to unpack if trying it yourself as github won't allow raw svg attachements).  The final rendering look correct:
 
![image](https://user-images.githubusercontent.com/576829/142035111-6d47b3d6-6fcf-48ff-88e7-390a2faa1fe7.png)

[tiger2.svg.zip](https://github.com/finos/waltz/files/7548529/tiger2.svg.zip)


I shall try the same steps tomorrow on SQL Server.

**Comment by davidwatkins73** [comment]
The table def is:

![image](https://user-images.githubusercontent.com/576829/142035661-0e2e1bfe-78f8-495b-b170-2d464e903ae5.png)

**Comment by davidwatkins73** [comment]
Just tested it here @ Deutsche with SQLServer and it worked correctly.

**Comment by strangetobefree** [comment]
Thanks David, really confused now, I'll ask our dba again if there's something we are missing here. We're running SQL Server. Any svg file so far has had the issue so I'll try your tiger and see tomorrow. Thanks again for taking a look

**Comment by davidwatkins73** [comment]
ok, just noticed I forgot to compress the tiger file.  Just knock off the `.zip` extension.

**Comment by davidwatkins73** [comment]
Closing, please re-open if you think this in error.
