### ISSUE TITLE
Questions pertaining to a Waltz Juju Charm

### ISSUE THREAD

**Issue by balbirthomas** [finos/waltz#5872]
Hi I would be grateful for a few clarifications that will unblock us on progressing a Waltz Charm

1. Does Waltz support scaling up ? I mean does Waltz support scaling through replication or federation of multiple running instances of Waltz. I ask because Juju supports scaling applications and would be keen to know if we should enable this feature for Waltz. 
2. What provisions should be made for allowing users to authenticate with the deployed Waltz charm. I understand user credentials are stored in the PostgreSQL database but it is not clear how in a typical production scenario such credentials are entered into the database.
3. Are the proposed configuration options sufficient for a Waltz charm? At present the plan is to support the following configuration options for a Waltz charm
- Credentials for database access
- Optional host address of database server. This is optional because the information can be automatically obtained through a relation with a database charm if a database charm is also used. This option is only useful if an external database is used.
- A boolean flag if database should be provisioned. This configuration option is intended to support use of the Waltz charm with an existing pre-populated database
- Optional external host name. This option is for associating a public domain name with the Waltz charm deployment.
4. Are Hybrid cloud deployments a typical use case for Waltz or is it typical to deploy both the database and Waltz in the same cloud ?

**Comment by davidwatkins73** [comment]
**1) Scaling:** currently Waltz scales horizontally by adding additional Java app servers.  We use a single database instance shared across these app servers, however we encourage reporting solutions to use a read-only of the database (in DB this clone only happens overnight).

**2) Authentication:**  Options include:
- Using built in own authentication, this use an out-of-the box JWT Authentication servlet filter and user credentials stored in the `user` table
- Header based filters (used in DB), we take the username from a provided header param.  This param is securely set via another (DB provided) sso filter and is also enforced at the Apache HTTPD layer.
- Installation provided filer class (configured by entering a class name in the `settings` table)

(WIP - will continue editing this response later)

**Comment by balbirthomas** [comment]
Thank you very much @davidwatkins73 . That was very useful. It gives us something to think of and get started.

**3) Proposed Charm**: Connectivity to charmed database(s) may be built into the Waltz Charm. Over such a "charm relation" Waltz obtains host address/port of database server. If the intent of the "batch loaders" is to populate data into a database then this feels like a backup/restore interface the database charm would/should provide. If "batch loaders" are used to specify table schemas and request creation of tables, this feels like a "set of requests" that may flow from the Waltz Charm to the Database charm over relation data. Your insights and experience of use cases, will certainly be very useful in refining these aspects of the Waltz Charm's behaviour. I will also engage with the Database charmers to gather their insights on the matter.

**Comment by davidwatkins73** [comment]
Hi @balbirthomas ,

The batch loaders will typically be responsible for populating the pre-existing database tables (these are created via the liquibase scripts).  Any custom tables required by the batch loaders will be typically provisioned in another schema.

At Deutsche we have a separate WAR deployed which contains a small UI front end over a quartz scheduler.  This coordinates all the periodic batch database updates  (typically those involving other systems).  Currently this part has not been open sourced, as I'm pretty certain the world doesn't need another job scheduler :)
