### ISSUE TITLE
Waltz Working Group : Charming Waltz with Juju - Wed 2 February 2022 - 9am ET / 2pm UK

### ISSUE THREAD

**Issue by mcleo-d** [finos/waltz#5882]
## Date
Wednesday 2 February 2022 - 9am ET / 2pm UK
Occurs the second Thursday of every month 

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene, roll call, welcome new people (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve previous meeting minutes - https://github.com/finos/waltz/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [ ] **Register Now** - https://github.com/finos/community/issues/152
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m00a97bac66d1324e1ca89b9bb4eb37c6

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 2554 479 5248

**Github Repo:** https://github.com/finos/waltz/

**Project Microsite:** https://waltz.finos.org

**Comment by balbirthomas** [comment]
Hi

**Comment by claudiubelu** [comment]
Hello

**Comment by kriscanonical** [comment]
Hi

**Comment by davidwatkins73** [comment]
Hi

**Comment by pedroleaoc** [comment]
Hi! :wave:

**Comment by davidwatkins73** [comment]
Thanks for today's session.  I found it very informative and has helped me get a much better grasp of the fundamentals.  Will let you know how we get on trying to replicate the scenario.

**Comment by balbirthomas** [comment]
Thank you for your kind words @davidwatkins73 . We should have this very pre-alpha version of the charm code, cleaned, reviewed and merged into main branch in approximately 2 days. Will update you through the Waltz slack channel as soon as this is done.
