### ISSUE TITLE
10th Feb 2022 - Waltz Project Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/waltz#5897]
## Date
Thursday 10th Feb 2022 - 10am ET / 3pm UK
Occurs the second Thursday of every month 

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve previous meeting minutes - https://github.com/finos/waltz/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [ ] Latest Waltz release updates - https://github.com/finos/waltz/releases
- [x] Charming Waltz with Juju working group update 
  - #5906
  - #5905
  - https://github.com/finos/waltz/issues/5895#issuecomment-1033838612
- [x] Waltz demo and Juju Charms working group update at DevOps Mutualization SIG
  - https://github.com/finos/devops-mutualization/issues/41 - **17th February 2022 at 12pm ET / 5pm GMT**
- [ ] Question : I understand there is a sample Waltz backend db with some test data available.  Could you give us the link to download?
  - We periodically release the test/sample database with releases (typically whenever the DDL changes). The latest is available from the releases page: [Release 1.39 · finos/waltz (github.com)](https://github.com/finos/waltz/releases/tag/1.39). Scroll down to the assets section and there will be a tar.gz with a postgres dump. 
![image001](https://user-images.githubusercontent.com/6029572/153373376-59c3704d-4776-4a82-8ae4-3654adf6114b.png)
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m00a97bac66d1324e1ca89b9bb4eb37c6

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 2554 479 5248

**Github Repo:** https://github.com/finos/waltz/

**Project Microsite:** https://waltz.finos.org

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by jgavronsky** [comment]
Jane @ FINOS here

**Comment by JWoodland-Scott** [comment]
Hello, Jess here! :)

**Comment by davidwatkins73** [comment]
Hello!

**Comment by kriscanonical** [comment]
Hi all
