### ISSUE TITLE
Create a FINOS waltz-integration-juju repository 

### ISSUE THREAD

**Issue by pedroleaoc** [finos/waltz#5905]
### Description

Hi folks, we have been working on a Charmed Operator for Waltz [here](https://github.com/pedroleaoc/waltz-integration-juju). It would be nice to have it moved to a FINOS repository as it consolidates the issues and allows us to have a project board under the FINOs org. My suggestion for name is 'waltz-integration-juju' to follow the same pattern used by other FINOS projects. 

Thanks!

cc @mcleo-d @maoo 

### Resourcing

We would like to collaborate on this feature

**Comment by mcleo-d** [comment]
Awesome @maoo - This is a fantastic update for today's Waltz project meeting - #5897

Thank you ! 👏🏻 💯

**Comment by davidwatkins73** [comment]
Hi @maoo,

Thanks for creating the project, however I think it may be better named `waltz-integration-juju` as that gives us a _pseudo_ integration namespace.  We can then keep `waltz-*` clear for _core_ waltz modules (e.g. `waltz-api`, `waltz-workflow`) and have projects with additional dependencies in the `waltz-integration-*` namespace.

**Comment by davidwatkins73** [comment]
Fantastic, thank you @maoo !

**Comment by mcleo-d** [comment]
Thank you @maoo and @davidwatkins73 for resolving this issue. I have now closed 🚀
