### ISSUE TITLE
10th March 2022 - Waltz Project Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/waltz#5957]
## Date
Thursday 10th March 2022 - 10am ET / 3pm UK
Occurs the second Thursday of every month 

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve previous meeting minutes - https://github.com/finos/waltz/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] Latest Waltz release updates - https://github.com/finos/waltz/releases
- [x] Waltz Working Group : Charming Waltz with Juju - Latest update from the group and next steps
- [ ] Go / No-Go Needed : https://github.com/finos/waltz/issues/5949
- [ ] https://github.com/finos/waltz/issues/5906 - Quick review to answer remaining questions.
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m00a97bac66d1324e1ca89b9bb4eb37c6

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 2554 479 5248

**Github Repo:** https://github.com/finos/waltz/

**Project Microsite:** https://waltz.finos.org

**Comment by davidwatkins73** [comment]
# Update

- **Minor releases**: [1.39.1](https://github.com/finos/waltz/releases/tag/1.39.1) and [1.39.2](https://github.com/finos/waltz/releases/tag/1.39.2).  Main enhancements:
  - Performance improvements in large exports
  - Report Grid setup UI improvements 
  - Report Grid includes any associated comments when showing survey answers
  - Updated from JUnit 4 to 5
- **Next release**, 1.40 is due on 22nd March 
  - More report grid improvements
    - now works over change initiatives
    - entity properties can be included (i.e. kind, lifecycle phase)
    - app group membership columns
- **Documentation** drive:
  - Detailed article on [flow classification rules](https://github.com/finos/waltz/tree/master/docs/features/flow_classification_rules)
  - Database schema documentation has begun #5935, approach described in this [blog](https://waltz.finos.org/blog/waltz/dev/jooq/liquibase/2022/02/18/database-dev.html)
  - Screencast on overhauled [survey screens](https://waltz.finos.org/blog/waltz/dev/2022/02/10/survey-improvements.html)
- **Community**
  - Juju
    - Charm sub project is nearing completion.  Waltz will hopefully be available on [CharmHub](https://charmhub.io/) soon.
    - Work is hosted on github @ [waltz-integration-juju](https://github.com/finos/waltz-integration-juju)

**Comment by pedroleaoc** [comment]
Hi :wave:

**Comment by JWoodland-Scott** [comment]
Hi!
