### ISSUE TITLE
Grid: Add datatype usage to report grid

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#5972]
### Description

Would be good to include data type usage to the grid.

- [x] Show data type (incl. usage kind, CONSUMER, DISTRIBUTOR etc.)
- [x] Allow roll ups 
- [x] Export
- [x] Add to column defs gui
- [x] Add to filters (maybe a new issue)
- [x] Bonus:  
    - [x] Date filters
    - [x] Cost filters
    - [x] App group 
    - [x] Date rendering
    - [ ] Show all apps / CI's (currently omits if no cell data)
    - [x] Stop filters being _forgotten_ when changing tabs

### Resourcing

We intend to contribute this feature

**Comment by davidwatkins73** [comment]
Just got kicked out of dod.  Current wip bug is that the data type tree nodes use the recursive `<self>` tag, but are not passing down the `selectionFilter`.   99% sure thats the problem :)

**Comment by JWoodland-Scott** [comment]
Index: waltz-data/src/main/java/org/finos/waltz/data/report_grid/ReportGridDao.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/waltz-data/src/main/java/org/finos/waltz/data/report_grid/ReportGridDao.java b/waltz-data/src/main/java/org/finos/waltz/data/report_grid/ReportGridDao.java
--- a/waltz-data/src/main/java/org/finos/waltz/data/report_grid/ReportGridDao.java	(revision 4e72dcadc9cb99e056b0f4384833e29725b306d4)
+++ b/waltz-data/src/main/java/org/finos/waltz/data/report_grid/ReportGridDao.java	(date 1648044332867)
@@ -40,6 +40,7 @@
 import org.springframework.stereotype.Repository;
 
 import java.sql.Timestamp;
+import java.sql.Types;
 import java.util.Comparator;
 import java.util.*;
 import java.util.function.Function;
@@ -725,9 +726,14 @@
                             .map(fieldName -> {
                                 ReportGridColumnDefinition colDefn = columnDefinitionsByFieldReference.get(fieldName);
 
-                                Object value = appRecord.get(APPLICATION.field(fieldName));
+                                Field<?> field = APPLICATION.field(fieldName);
+                                Object rawValue = appRecord.get(field);
 
-                                if (value == null) {
+                                String textValue = isTimestampField(field)
+                                        ? String.valueOf(DateTimeUtilities.toLocalDate((Timestamp) rawValue))
+                                        : String.valueOf(rawValue);
+
+                                if (rawValue == null) {
                                     return null;
                                 }
 
@@ -736,7 +742,7 @@
                                         .subjectId(appRecord.get(APPLICATION.ID))
                                         .columnEntityId(colDefn.columnEntityId())
                                         .columnEntityKind(EntityKind.APPLICATION)
-                                        .text(String.valueOf(value))
+                                        .text(textValue)
                                         .entityFieldReferenceId(colDefn.entityFieldReference().id().get())
                                         .build();
                             }))
@@ -745,9 +751,15 @@
         }
     }
 
+    private boolean isTimestampField(Field<?> field) {
+        DataType<?> dataType = field.getDataType();
+        int sqlType = dataType.getSQLType();
+        return sqlType == Types.TIMESTAMP;
+    }
+
 
     private Set<ReportGridCell> fetchChangeInitiativeFieldReferenceData(GenericSelector selector,
-                                                                       Set<Tuple2<ReportGridColumnDefinition, EntityFieldReference>> requiredChangeInitiativeColumns) {
+                                                                        Set<Tuple2<ReportGridColumnDefinition, EntityFieldReference>> requiredChangeInitiativeColumns) {
 
         if (requiredChangeInitiativeColumns.isEmpty()) {
             return emptySet();
@@ -849,9 +861,15 @@
                                 .getOrDefault(templateId, emptySet())
                                 .stream()
                                 .map(fieldRef -> {
-                                    Object value = surveyRecord.get(SURVEY_INSTANCE.field(fieldRef.fieldName()));
+
+                                    Field<?> field = SURVEY_INSTANCE.field(fieldRef.fieldName());
+                                    Object rawValue = surveyRecord.get(field);
 
-                                    if (value == null) {
+                                    String textValue = isTimestampField(field)
+                                            ? String.valueOf(DateTimeUtilities.toLocalDate((Timestamp) rawValue))
+                                            : String.valueOf(rawValue);
+
+                                    if (rawValue == null) {
                                         return null;
                                     }
 
@@ -860,7 +878,7 @@
                                             .subjectId(surveyRecord.get(SURVEY_INSTANCE.ENTITY_ID))
                                             .columnEntityId(templateId)
                                             .columnEntityKind(EntityKind.SURVEY_TEMPLATE)
-                                            .text(String.valueOf(value))
+                                            .text(textValue)
                                             .entityFieldReferenceId(fieldRef.id().get())
                                             .build();
                                 });
