### ISSUE TITLE
FINOS London Meetup - Waltz - Wednesday 20th April from 5pm GMT

### ISSUE THREAD

**Issue by mcleo-d** [finos/waltz#5986]
@davidwatkins73, @JWoodland-Scott, @ljubon, @kriscanonical and @pedroleaoc,

FINOS is hosting our next in-person and hybrid London meetup on **Wednesday 20th April from 5:30pm BST** in the City of London and I'd like to propose the following talks by David, Jess and the Waltz community. It would be great to get your feedback.

### Talk 1
**Introducing Waltz the Open Enterprise Project**

Waltz is Deutsche Bank's open source project, that has been contributed to FINOS, that allows you to visualise and define your organisation's technology landscape. Think of Waltz as a structured Wiki for your enterprise architecture.

A core belief behind Waltz is that technology information should be accessible by everyone within your organisation. Furthermore, employees are your best source of information about your technology landscape and should therefore be empowered to enhance and correct data.

Join David Watkins and Jessica Woodland-Scott from Deutsche Bank as they introduce Waltz, the 2022 evolution of the project, and what it's like to be open source contributors in banking.

### Talk 2
**Getting Waltz Up and Running in your Financial Services Setting**

Throughout 2022 the Waltz project community has worked tirelessly to make Waltz more accessible to banks and open source development by utilising Juju, Charms and Docker.

Join Pedro Leão da Cruz, Product Lead from Canonical, alongside the Waltz team, for a guided tour of how to get Waltz up and running in your financial services setting using containers and kubernetes.

During the demo, FINOS and the Waltz team will announce a Public Waltz Demo Instance hosted on AWS that's fully built from new Waltz releases using a GitHub driven SDLC!

**Comment by davidwatkins73** [comment]
Venue: https://www.google.com/maps/place//data=!4m2!3m1!1s0x48761cad5bcfeb13:0x5b93195d093400af?source=g.page.share

**Comment by davidwatkins73** [comment]
Topic ideas:

- Overview
- Core concepts
- BoMs
- Use cases:
  - surveys
  - payment apps
  - process diagram overlays

**Comment by mcleo-d** [comment]
## Talks
- https://github.com/finos/waltz/tree/master/docs/talks/finos-20211004-getting-started

**Comment by mcleo-d** [comment]
@davidwatkins73, @JWoodland-Scott, @kriscanonical, @pedroleaoc, @maoo and @robmoffat,

I have updated the main description of the FINOS Waltz meetup on 20th April to reflect the event registration details for in-person and Zoom here ... https://zoom.us/webinar/register/WN__Fug8-UKQM2YgdcqRrQcKg
 
Please review the meetup description prior to the call scheduled for 13th April to make sure all is on track for the event the following week ... https://github.com/finos/waltz/issues/5986#issue-1186575487

I particularly need to know all is okay for the delivery of #5906 with @maoo and @robmoffat where the Waltz Public Instance will be demonstrated as part of the event.

Feel free to comment below. Thanks!

James.
