### ISSUE TITLE
14th April 2022 - Waltz Project Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/waltz#6007]
## Date
Thursday 14th April 2022 - 10am ET / 3pm UK
Occurs the second Thursday of every month 

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve previous meeting minutes - https://github.com/finos/waltz/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] #5906
- [x] #6001 - **May 17th - Next Waltz Release**
- [x] #6003
- [x] Waltz - Open Source in Finance Hybrid Meetup - **Wednesday 20th April @ 5:30pm BST** - Register Here - https://www.finos.org/hosted-events/2022-04-20-finos-open-source-in-finance-meetup-london
- [x] https://github.com/finos/community/issues/183
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m00a97bac66d1324e1ca89b9bb4eb37c6

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 2554 479 5248

**Github Repo:** https://github.com/finos/waltz/

**Project Microsite:** https://waltz.finos.org

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by niamhoparker** [comment]
Hello

**Comment by JWoodland-Scott** [comment]
Hi! :)

**Comment by claudiubelu** [comment]
Hello. :)

**Comment by mcleo-d** [comment]
May 17th next Waltz release.
