### ISSUE TITLE
Cleanup: remove uses of deprecated MapUtilities.groupAndThen

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#6032]
### Description

`MapUtilities.groupAndThen(keyFn, valFn, xs)` => `MapUtilities.groupAndThen(xs, keyFn, valFn)`

Rationale: helps with code completion having them in this order.

### Resourcing

We would like to add this request to the Waltz team's task backlog

**Comment by ahmedsaheed** [comment]
Hi @davidwatkins73 I would like to make a PR draft on this issue. But I'd appreciate a more concise explanation as to what i need to do and where these deprecated `MapUtilities.groupAndThen` can be found. Thanks
