### ISSUE TITLE
Create actor doesn't let you set external id however this can be edited later? Should maybe be automatic from name.

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#6058]

**Comment by judofosu** [comment]
Hi, it seems the external id can be set now when creating an actor. Is the focus automatically setting the external id from the name?

**Comment by davidwatkins73** [comment]
I think this issue should have been closed when #6578 was delivered (PR: #6582  specifically [this file change](https://github.com/finos/waltz/pull/6582/files#diff-a7c2d11ce36328b178dd9a2a426eded8d236af05207efbb4df201c5a41b2e2ef) ).  
Thanks for bringing it to our attention and apologies for wasting your time looking into this.
