### ISSUE TITLE
9th June 2022 - Waltz Project Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/waltz#6089]
## Date
Thursday 9th June 2022 - 10am ET / 3pm UK
Occurs the second Thursday of every month

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve previous meeting minutes - https://github.com/finos/waltz/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] https://github.com/finos/waltz/issues/6089#issuecomment-1150824605 - @davidwatkins73 
- [x] https://github.com/finos/waltz/issues/5906#issuecomment-1097940997 - @pedroleaoc, @claudiubelu
- [x] [Get involved in testing Waltz Juju and Charms installation](https://www.linkedin.com/posts/jamesmcleod_opensource-qualityengineering-qualityengineer-activity-6937077532353556480-r7lF) - @mcleo-d
- [x] [Open Source in Finance Forum in London](https://events.linuxfoundation.org/open-source-finance-forum-london) on July 13th 2022 - @mcleo-d 
- [x] AOB, Q&A & Adjourn (5mins)

## Open Source in Finance Forum London, July 13th 2022

Register below for the FINOS [Open Source in Finance Forum](https://events.linuxfoundation.org/open-source-finance-forum-london/) in London on July 13th 2022 👾💥

Open Source in Finance Forum is the only conference dedicated to driving collaboration and innovation in financial services through open source software and standards.

We bring together experts across financial services, technology, and open source to engage our community in stimulating and thought-provoking conversations about how to best (and safely) leverage open source software to solve industry challenges.

FINOS members employees are eligible to receive complimentary registration as part of their company’s membership. Please email [osff@finos.org](mailto:osff@finos.org) to request the Finos Member access code.

Register and find out more 👉🏻 https://events.linuxfoundation.org/open-source-finance-forum-london/

<a href="https://events.linuxfoundation.org/open-source-finance-forum-london/"><img src="https://user-images.githubusercontent.com/6029572/171230930-a68f99a3-ac8d-4738-8054-87af2d45b544.png" width="85%" /></a>

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m00a97bac66d1324e1ca89b9bb4eb37c6

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 2554 479 5248

**Github Repo:** https://github.com/finos/waltz/

**Project Microsite:** https://waltz.finos.org

**Comment by davidwatkins73** [comment]
**Topics:**

- Recent [1.41 release](https://github.com/finos/waltz/releases/tag/1.41)
  - Improved calendar view
  - On demand mesurable attestations (i.e. Functional Taxonomy mappings)
  - Actor improvements
  - Survey predicates based on app characteristics (e.g. in-house vs third-party)
- Upcoming 1.42 release
  - 'Bank on a Page'
  - Enhanced Permissions
  - Library update
  -

**Comment by davidwatkins73** [comment]
Hello !  (Dave + Jess)

**Comment by mcleo-d** [comment]
Hi there 👋🏻

**Comment by claudiubelu** [comment]
Hello!
