### ISSUE TITLE
Assessment Definition: grouping

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#6098]
### Description

There can be a _lot_ of assessment definitions in Waltz.  This rapidly turns the assessment section into a long list.  This is somewhat mitigated by allowing users to 'favourite' some assessments but it is still overwhelming.

Proposal is to add grouping support.  A new table defines the available set of groups: `assessment_definition_group`
Probably looks a bit like:

id | name | description | icon | _colour_ ?
--- |  --- | --- | --- | ---
1 | cloud | Cloud assessments | cloud | blue
2 | regulatory | Regulatory | check-list | green

Then in the current `assessment_definition` table we add a (nullable) column which references this table.

Tasks:

- [ ] ~Create table~
- [ ] Add column to existing def table
- [ ] ~fk (**no** cascade delete!)~
- [ ] Update UI, null references in def table should go to an _on-the-fly_ default group (e.g. 'Other')
  - [ ] Assessment section
  - [ ] Agg Overlay (overlay + filter)
  - [ ] Report Grids
  - [ ] ...other ?
  - [ ] **Take opportunity to standardise picker if reqd!**
- [ ] Definition creator, allow selection of (pre-existing) groups

### Resourcing

We intend to contribute this feature

**Comment by JWoodland-Scott** [comment]
Tactically going with an additional `definition_group` column on the` assessment_definition` table
