### ISSUE TITLE
Database search and filtering

### ISSUE THREAD

**Issue by mharward-gr** [finos/waltz#6318]
### Description

Currently search and filter functionality is supported for a lot of waltz entities, including servers, we've noticed that this has not been implemented for databases. This seems like a useful feature and our DB teams would get value from this functionality.

![image](https://user-images.githubusercontent.com/101175118/203965064-8a4a34cd-547d-4919-8c50-fdffe6e911f6.png)

### Resourcing

We would like to add this request to the Waltz team's feature backlog

**Comment by davidwatkins73** [comment]
Agreed, this would be a good addition.  Will add it to 1.47 (due early in the new year).  Thanks for the suggestion

**Comment by davidwatkins73** [comment]
<img width="696" alt="image" src="https://user-images.githubusercontent.com/576829/224544148-9d3d924a-c5d3-435f-8f8a-e7df2ca8c81a.png">

**Comment by davidwatkins73** [comment]
Hi @mharward-gr ,  just finished the work on this issue.  Should be included and packaged as part of 1.48 (due end of March)

**Comment by mharward-gr** [comment]
Thank you for this @davidwatkins73, very much appreciated.
