### ISSUE TITLE
Icons: fontawesome icons not working inside svg

### ISSUE THREAD

**Issue by JWoodland-Scott** [finos/waltz#6350]
### Description

Create custom icons

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

See icon related to entity

### Actual Result

See empty box

**Comment by davidwatkins73** [comment]
@JWoodland-Scott has added custom icons via the d3 symbol mechanism.

The result looks like:

<img width="85" alt="image" src="https://user-images.githubusercontent.com/576829/218341272-5f295e8f-1a70-48d3-8790-04839bfe89b1.png">
