### ISSUE TITLE
Bulk Involvement Loader: failing/timeout on large data sets

### ISSUE THREAD

**Issue by JWoodland-Scott** [finos/waltz#6412]
### Description

Appears to be due to the person aliases

### Waltz Version

1.46

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

Resolved rows appear

### Actual Result

Error message 'undefined' appearing

**Comment by davidwatkins73** [comment]
Taken execution down from >30 secs to ~2-3 secs.
