### ISSUE TITLE
"Build" link in waltz/docs/README.md not pointing to build.md file and giving 404 error

### ISSUE THREAD

**Issue by thush-lp** [finos/waltz#6414]
### Description

In the waltz/docs/README.md file, the "Build" link within "Development" points to "build" rather than "build.md". So, when you click on the Build link, it throws a 404 missing page error.

I have tested changing the file locally and it works correctly.

### Waltz Version

1.46

### Steps to Reproduce

1. View the waltz/docs/README.md file in Git
2. Click on the "Build" link

### Expected Result

Clicking on the "Build" link should open the build.md file.

### Actual Result

The link in the waltz/docs/README.md file points to "build" rather than "build.md", so you see a missing page 404 error.

**Comment by msagi** [comment]
/assign 

Let me fix it
