### ISSUE TITLE
Assessments: bulk loader broken by MVAs

### ISSUE THREAD

**Issue by JWoodland-Scott** [finos/waltz#6452]
### Description

Issues with removing, replacing and adding, beyond the initial load of values. Incorrectly identifying when a rating needs creating or updating.

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

Replace removes existing ratings and replaces with the new list. 
Individual remove removes that specific rating for the application.
Add will add any new ratings not in the existing ratings list.
Will update values when single value assessment, will create new ratings when multi valued assessment

### Actual Result

Error message that violating unique key constraint

**Comment by davidwatkins73** [comment]
Done some testing locally on home machine.  Seems to be working fine.
