### ISSUE TITLE
Best practice Waltz version upgrade?

### ISSUE THREAD

**Issue by msagi** [finos/waltz#6491]
### Description

Dear @davidwatkins73 and @JWoodland-Scott ,

We are running a relatively old version of Waltz and thinking about bringing it up to date. Is there any recommended approach to do this?

Thank you for your support in advance!

**Comment by davidwatkins73** [comment]
Hi @msagi ,  we'll pull together a page on how best to approach this.  Should be done in a day or so.

**Comment by JWoodland-Scott** [comment]
Hi @msagi, the updated docs have just been added: https://github.com/finos/waltz/blob/master/docs/development/upgrade.md

**Comment by msagi** [comment]
Thank you @JWoodland-Scott ! We will take a look and try to do some test upgrades on our instance 🙏🏻🙂
