### ISSUE TITLE
Report Grid: person view should included non-direct apps

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#6602]
### Description

currently only shows direct apps which causes confusion between the two numbers on the person page

### Resourcing

We would like to add this request to the Waltz team's feature backlog

**Comment by judofosu** [comment]
I was looking at this issue and would appreciate some clarification. Could you please specify the two numbers on the person page causing the confusion

Also, is this the desired outcome we are aiming for? Are we looking to have the indirect apps displayed in the report grid, similar to how the direct ones are shown?
![Screenshot (152)](https://github.com/finos/waltz/assets/139548954/7ee4b884-d8c2-41b9-958d-2891aa9d6959)

**Comment by davidwatkins73** [comment]
Hi, this issue relates to a workaround we needed to add to the code to ensure grids were performant for users with large numbers of indirect apps.

Direct apps are those where the person has an explicit involvement (e.g. Adam is the domain architect for the app).
Indirect apps are those where someone who reports to the person has a direct involvement with the app (e.g. Bob, manages Adam, indirectly is involved with the app (via Bob)).

To see the difference now you can check that the number of apps in the grid is <= the number of apps being reported at the top of the screen.  If the numbers are all equal then the user only has direct involvements.  Go up the hierarchy tree to their mgr until the numbers diverge...

----

The offending code is here:

https://github.com/finos/waltz/blob/83c0311a43e57675f5c51730a946ae12c824d67e/waltz-service/src/main/java/org/finos/waltz/service/report_grid/ReportGridService.java#L113

It probably just need to skip the `modify....` method (and remove the method if it's no longer used).
I'm pretty certain the reason we had the workaround is no longer needed, we were missing a periodic rebuild of stats and indexes on some of our tables which was causing uneven performance.

Hope this helps.
