### ISSUE TITLE
Survey Question: support Legal Entity (multi) picker

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#6619]
### Description

- Should store the legal entity name as well as the reference (in case the LE is removed later)
- Perhaps 2 versions (single select and multi select)
- Bulk entry ?

- can this be generalized to bulk (non-hier) entity support, e.g.
  - application
  - people
  - groups

### Resourcing

We intend to contribute this feature

**Comment by kamransaleem** [comment]
**from survey response view mode**

![image](https://github.com/finos/waltz/assets/3029467/e0d77f63-fcee-442b-9203-be312be90a09)

**From edit mode**

![image](https://github.com/finos/waltz/assets/3029467/66e31610-98d7-44c4-bced-c5f5d5c28c81)

**After resolving the identifiers**

![image](https://github.com/finos/waltz/assets/3029467/2608cc0d-b67d-40a5-ba1d-bcee75dc3981)
