### ISSUE TITLE
Allow org unit people to be filtered by direct involvement

### ISSUE THREAD

**Issue by mharward-gr** [finos/waltz#6629]
### Description

The People section, within a Org Unit, currently shows people directly involved with the Org Unit plus those involved with parent Org Units as well. In some cases this is very helpful as it implicitly shows people higher in the organisational hierarchy who likely have a relationship with this team.

However, we have found that most of the time users are most interested in those with a direct involvement with the org unit. e.g. who is the product owner / manager / architect directly involved with this org unit, rather than a wider role with a parent org unit.

We suggest some kind of filter or toggle in the UI between a direct involvement and indirect involvements. Possibly defaulting to showing direct involvements.

Thank you for considering this and please let us know if we've missed something!

### Resourcing

We would like to add this request to the Waltz team's feature backlog

**Comment by JWoodland-Scott** [comment]
Hi Matthew,
Thanks for raising an issue for this. It's also come up recently with regards to change initiatives which demonstrate the same behaviour. We're likely to look at this in the 1.51 release which is targeting the end of June, so will add this issue to the milestone.

**Comment by mharward-gr** [comment]
@JWoodland-Scott this is really great and very much appreciated, thank you!!
