### ISSUE TITLE
Data Hierarchy not showing child elements 

### ISSUE THREAD

**Issue by RussGreenCode** [finos/waltz#6661]
### Description

When adding the Data Hierarchy to Waltz and navigating to a particular element you can see if the element has a parent and navigate to the parent - but if the element has a child, you can not see it, and you have to go back to the top level navigation to move around.

Would be good to show both the Parent and any Children elements on the element view.

### Resourcing

We would like to add this request to the Waltz team's feature backlog

**Comment by davidwatkins73** [comment]
![image](https://github.com/finos/waltz/assets/576829/b38b2c76-f35a-455c-8188-9c1fb1c77848)
