### ISSUE TITLE
View of all applications

### ISSUE THREAD

**Issue by mharward-gr** [finos/waltz#6677]
### Description

Our users have asked for an easy-to-access view of all applications.

At present, Waltz's main mechanism for viewing all applications is via either a high level Org Unit or via a curated Application Group. This is problematic because:

* New users to Waltz find it hard to navigate to an equivalent view
* If there are multiple top level org units, getting a complete picture of your estate becomes harder
* If an application references a non-existent org unit, it's not visible in these org units and therefore gets almost lost in Waltz (yes, you can find them in the System Admin / Orphans page, but this only works for Admins and is pretty hidden away)

What our users have suggested is a new 'Applications' link on the header bar that shows all applications (no matter who owns them). It would contain the same kind of panels shown when viewing an org unit or application group. e.g. Applications, Application Costs, Technologies, Statistics, Application Complexity etc... (probably not People, Bookmarks, ....)

This could also be linked to from the breadcrumb trail when viewing an application. e.g.
![image](https://github.com/finos/waltz/assets/101175118/99a94b8c-5972-4b6e-8c60-9408d34f000a)

Thank you for considering this!

### Resourcing

We would like to add this request to the Waltz team's feature backlog

**Comment by davidwatkins73** [comment]
Associated PR delivers this:

<img width="947" alt="image" src="https://github.com/finos/waltz/assets/576829/7559a70c-30a0-4a56-97c4-7dece81beba8">


It uses a `settings` table entry to control which grid id use.  
This can be set with a stmt like:

```
insert into settings (name, value, description)
values (
  'feature.application-list.default-report-grid-id', 
  8, -- report grid id to use 
  'When showing the basic app list, this is id of the app grid to use');
```

If the setting is not specified the report grid picker will be shown (and an non-breaking error will be logged to the console) 

<img width="1463" alt="image" src="https://github.com/finos/waltz/assets/576829/5299036c-771f-4d86-baba-8d0198489ede">

**Comment by davidwatkins73** [comment]
We will look to add the dynamic sections (bookmarks etc) in a subsequent release.  (I'll create a new issue linked to this one)

**Comment by davidwatkins73** [comment]
After consulting with @JWoodland-Scott we have decided to do the full implementation now, so #6686 is now also completed:

<img width="948" alt="image" src="https://github.com/finos/waltz/assets/576829/e867ad81-ee60-421c-877f-9898753368f9">

**Note** the previous comment about using a setting can be ignored.  We are now just using a standard report-grid section.

**Comment by mharward-gr** [comment]
Thank you very much @davidwatkins73 and @JWoodland-Scott, this is great and really appreciated!
