### ISSUE TITLE
Navaids: Add support for markdown descriptions

### ISSUE THREAD

**Issue by JWoodland-Scott** [finos/waltz#6709]
### Description

Included on the measurable category view

### Resourcing

We would like to add this request to the Waltz team's feature backlog

**Comment by davidwatkins73** [comment]
We want to be able to rich information under nav aid diagrams.  Currently the descriptions are just plain text but if we render them as markdown we can make them more useful.  Initial uses include:

- legends (using colorful text)
- links to confluence etc

**Comment by JWoodland-Scott** [comment]
Had to add &#xfe0e; to allow unicode character to inherit text colour
