### ISSUE TITLE
Measurable Category: should support a static panel with information above the diagrams

### ISSUE THREAD

**Issue by JWoodland-Scott** [finos/waltz#6710]
### Description

Option to move the existing 'About' static panel or create a new one.

May need to move the exports under tree

### Resourcing

We would like to add this request to the Waltz team's feature backlog

**Comment by davidwatkins73** [comment]
Moving the panel looks good, however the static panel titles look a bit out of place.
Decided the best solution is to make static panel optionally render a title based on the presence of the `static_panel::title` value in the database.  This in turn means we will need to updated the DDL (the column is currently non-nullable) and update the static panel admin screens to relax the _required_ constraint.

**Comment by davidwatkins73** [comment]
Now that panel titles are nullable, we need something better to show in the panel list.   Decision is to show the title and fallback to showing an italicized version of the first 50 chars of the content if the title is not available.
