### ISSUE TITLE
Overlay Diagrams: Add the ability to sort diagram cells according to the data driven position

### ISSUE THREAD

**Issue by JWoodland-Scott** [finos/waltz#6711]
### Description

Measurables can be assigned a position, would be good to have a builder control to support ordering by this. Consider groups on a diagram can be composed of multiple entity kinds / categories. 

### Resourcing

We would like to add this request to the Waltz team's feature backlog

**Comment by davidwatkins73** [comment]
**Plan**:

- Need to update the builder code in `waltz-ng/client/entity-diagrams/components/entity-overlay-diagrams`
- Add a button to sort the direct children of a group by position (if available), falling back to name

**Challenges**:

- Position may not be available as it may deal with simple refs
- Position not supported across all entity kinds
- Groups could contain a pick-n-mix selection of children, therefore auto sorting may yield odd results

**Comment by davidwatkins73** [comment]
Noticed the initial name for the starting group implies it is the diagram title, which is misleading.  Updating to `Initial Group`.

![image](https://github.com/finos/waltz/assets/576829/87102986-68de-4193-98a5-969ac10ead43)

**Comment by davidwatkins73** [comment]
By adding a bit of code in the `EditItemsPanel::addChildren` method we can see that the `directChildren` variable is used to propulate the child entries.   This variable is, in turn, loaded from the `MeasurableEndpoint::findByParentId` endpoint.  If we make the associated DAO method do a sort then this _should_ fix the problem:

![image](https://github.com/finos/waltz/assets/576829/017e3c80-fd12-4489-a65d-04b4ec324f36)

**Comment by davidwatkins73** [comment]
We've added sorting to the person and data type children selector.  Though these only work off `name` as they have no `position` field.
