### ISSUE TITLE
Involvement: Hide filter buttons in a details section

### ISSUE THREAD

**Issue by JWoodland-Scott** [finos/waltz#6726]
### Description

Details tag: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

Would be good to see if we can use this more often across waltz where filters appear

### Resourcing

We would like to add this request to the Waltz team's feature backlog

**Comment by davidwatkins73** [comment]
Editing `involved-people-section.html`.  Going to put the `details/summary` tags around the filters.

**Comment by davidwatkins73** [comment]
Had to add some styling to make it work nicely.

**Collapsed**
![image](https://github.com/finos/waltz/assets/576829/878d2203-8d08-498a-9c27-6e3934f69d9f)

**Expanded**
![image](https://github.com/finos/waltz/assets/576829/639413ec-6f9b-4d80-8810-3ca8489feef6)

**Comment by davidwatkins73** [comment]
Also added to change initiatives section:

**Expanded**
![image](https://github.com/finos/waltz/assets/576829/c532935d-91ae-4805-ae94-4ef97c97433b)
