### ISSUE TITLE
Change Initiatives: increase size of name column to varchar(255)

### ISSUE THREAD

**Issue by JWoodland-Scott** [finos/waltz#6746]
### Description

Currently limited to 128, sometimes names can exceed this length. The name.type length specified in properties is 255, should update to this, 

### Resourcing

We would like to add this request to the Waltz team's feature backlog

**Comment by davidwatkins73** [comment]
perhaps we need to introduce a new alias in the `db.properties.xml` - something like `${name-long.value}`
