### ISSUE TITLE
Ability to evaluate text values from other columns in a Derived Column within a Report Grid

### ISSUE THREAD

**Issue by TL41** [finos/waltz#6915]
### Ability to evaluate text values from other columns in a Derived Column within a Report Grid
---
I don't think we were able to evaluate the Text values of the columns within the Report Grid.

Ex. The idea is to have a derived column 'Compliant?' which evaluates the text inputs of the survey values in the report grid. something like - if API Security == 'SSL' and Authorization == 'SAML' and ... , then 'Compliant?' = 'YES'

I see some newly added features around date evaluations, but I don't think there's anything there regarding text evaluations.

@davidwatkins73 I built a small function to accomplish this that I can contribute, unless there's already an existing function for this that I'm missing

### Resourcing

We intend to contribute this feature

**Comment by davidwatkins73** [comment]
We have derived cells which do similar types of calculation.  For example:

![image](https://github.com/finos/waltz/assets/576829/fca3e60c-3bc4-40ac-8e12-4a51d2a8c7fb)


**As Text**
```
cell('CRIT').textValue() == 'Critical'
&&
cell('INV_STATUS').textValue() == 'Invest'
   ? mkResult("Super important")
   : null;
```

**Comment by TL41** [comment]
@davidwatkins73 thank you for the info!

Would you like me to enhance that section on the page to provide some examples for Text and Date Fields, in addition to what's there for Cell Populating checks?

**Comment by davidwatkins73** [comment]
@TL41 Having some more embedded help would be great.  We could also look to write some more helper functions for the [ReportGridEvaluatorNamespace](https://github.com/finos/waltz/blob/master/waltz-service/src/main/java/org/finos/waltz/service/report_grid/ReportGridEvaluatorNamespace.java) which may make it easier to write these operations.  

We kinda guessed what would be useful when we first created the functions in the namespace.   Looking through some of ours we see things like:

```
cell('Staging Flag').textValue().replaceAll("\r\n", "").replaceAll("\n", "").toLowerCase() =~ '.*no - .*' || cell('Staging Flag')== null
    ? mkResult('Y')
    : null
```
and 

```
cell('Availability_Scope').textValue() != "Removed from Scope" && cell('Availability_Scope').textValue() != null
    ? mkResult(cell('Availability_Scope').textValue())
    : null
```

We could maybe look to introduce some functions/predicates like:

- `lc('CELL_REF')`
- `in('CELL_REF', ['v1', 'v2'])`
- `eq('CELL_REF', 'value')`
- `like('CELL_REF;, '.*pattern')`

**Comment by TL41** [comment]
@davidwatkins73 I opened a new issue to track your suggestion. It could be something we can help as we prioritize open work items.

**Comment by TL41** [comment]
In case anyone comes across this, there are additional details around Report Grids and Derived Columns here: [report-grids/README.md](https://github.com/finos/waltz/blob/master/docs/features/report-grids/README.md)
