### ISSUE TITLE
Add Additional APPLICATION_KIND: 'UNKNOWN' and 'INTERNAL_AND_EXTERNAL'

### ISSUE THREAD

**Issue by TL41** [finos/waltz#6916]
### Description

request to add new values for APPLICATION_KIND of 'UNKNOWN' and 'INTERNAL_AND_EXTERNAL'

---
1) 'UNKNOWN' would be a placeholder for cases where we don't yet have information on the application type

2) If we're using the 'Type' to classify the 'Application Hosting' values, then it should be a binary 'Internal Hosted' or 'External Hosted'

But if we're using the 'Type' field to classify 'Application Facing', it could be 'Internal', 'External' or 'Both'
- The intentional of 'INTERNAL_AND_EXTERNAL' is for Applications that are classified as both Internal and External facing

I think the additional option would give organizations the ability to utilize the Type field based on their specific need

Happy to contribute this unless there's a good way to accomplish this now. Also open to revisions on any naming conventions

Further, these might be two things an organization would want to see simultaneously in the future

### Resourcing

We intend to contribute this feature

**Comment by davidwatkins73** [comment]
I think this may be better represented via an application assessment:

- 'Facing': 'Internal' / 'External' / 'Both'
- ...or a muti valued assessment can remove the need for 'Both'  

Currently it seems kind of orthogonal to the kind and would lead to lots of permutations (Internal Customised, External Customised, Both Customised, Internal In House, External In House etc)

However, that said, our current inclusion of 'INTERNALLY_HOSTED' and 'EXTERNALLY_HOSTED' has a similar problem  (we don't actually use either of them) and should be represented via a 'Hosting' assessment or similar.

Adding 'UNKNOWN' is a good idea.

**Comment by davidwatkins73** [comment]
The other option for this is for us to move it into the `enum_value` table to allow it to vary per customer.  We did something similar to data formats a year or so ago  (we wanted to add some custom formats for the bank) :  

- https://github.com/finos/waltz/issues/6167

**Comment by TL41** [comment]
@davidwatkins73 thanks for the feedback. I can roll back most of the changes and just include the 'UNKNOWN' portion - does that work for a good short-term solution? 

I can then open and track a new issue for possibly implementing the enum_value solution

Note: this isn't a pressing matter and isn't blocking anything


Also: which subset of the Application Kind values would you recommend we select from? I know that can be implementation specific, but maybe to rephrase - which values would you say are core to the intended function of 'Application Kind'?

**Comment by davidwatkins73** [comment]
I think that all of them  without the two HOSTED options   (+ the proposed 'UNKNOWN').  Giving:

VALUE | NAME | DSECRIPTION
-- | -- | --
CUSTOMISED | Customised | Thirdparty application which has been customised
EUC | End User Computing | End user produced applications
EXTERNAL | External to the organisation | Applications which are completely external to the organization
~EXTERNALLY_HOSTED~ | ~Externally Hosted~ | ~Applications which are hosted externally, typically SaaS solutions~
IN_HOUSE | In House | Applications which have been developed internally
~INTERNALLY_HOSTED~ | ~Hosted Internally~ | ~Thirdparty applications which are hosted on premises~
THIRD_PARTY | Third Party | Applications developed by a third party
**UNKNOWN** | **Unknown** | **Not known**

**Comment by TL41** [comment]
Thanks @davidwatkins73 - I'll make note of this and look to avoid using 'EXTERNALLY_HOSTED' and 'INTERNALLY_HOSTED'

I've updated the PR https://github.com/finos/waltz/pull/6921 to only add 'UNKNOWN'
