### ISSUE TITLE
Software Package: show vulnerability details associated to software versions

### ISSUE THREAD

**Issue by TL41** [finos/waltz#6936]
### Description

Is there a way to navigate to the vulnerability description in the UI?

On the /software-package endpoint, I can see an indicator and and vulnerability count, but nothing intuitive (to me) with how to find details on said vulnerabilities.

Starting this is an enquiry, let us know if there is an existing feature or if we can create a request for one.

source:
https://github.com/finos/waltz/blob/master/waltz-ng/client/software-catalog/components/versions/software-package-versions.html

this only seems to show a count of associated descriptions, but no description nor link to details on those vulnerabilities

---
I see this added the feature: https://github.com/finos/waltz/issues/5073

**Comment by davidwatkins73** [comment]
I agree this feature would be useful.  At our org they decided against implementing it as there was concern about showing direct vulnerabilities against an application.  A sibling application (non-oss) does show specific vulnerabilities but is locked down to be viewable only by application owners. 

Currently Waltz _does_ take vulnerability/severity counts for display so we can scoreboard parts of the org.    
Happy for this feature to be added but we may need to either put enhanced security around it, or have a feature flag to completely disable (we already have some feature flags for cost exports and the roadmap section).
