### ISSUE TITLE
SSO Oauth Implementation Bug - missing curly bracket

### ISSUE THREAD

**Issue by TL41** [finos/waltz#6938]
### Description

Hi @davidwatkins73,

I'm testing with the latest build and it wasn't working as I would expect. Did some debugging and found a missing curly bracket in 

https://github.com/finos/waltz/commit/268b79f5ebf2c0d382879c5a94ccae01914e8be6

``` @Value("${oauth.token_url:oauth.token_url config option not provided") ```

vs. 

``` @Value("${oauth.token_url:oauth.token_url config option not provided}")```

I'll also clean up the default values 

### Waltz Version

current

### Steps to Reproduce

1.
2.
3.
...

**Comment by TL41** [comment]
I think I see a few other small issues. I'll compile those and create a PR

**Comment by davidwatkins73** [comment]
Ah sorry - thought I'd kicked off a full build.

**Comment by davidwatkins73** [comment]
Merged.  Thanks for the PR.
