### ISSUE TITLE
Logical Flows: add external id column

### ISSUE THREAD

**Issue by OscarGreen03** [finos/waltz#6944]
### Description

adding a column to the `logical_flows` table, so they can be separately identified 

### Resourcing

We intend to contribute this feature

**Comment by davidwatkins73** [comment]
Checklist:

- [ ] liquibase
    - [ ] add column
    - [ ] (optional) add column remarks to document it in the schema

If you want the external id to be seen in the ui:

- [ ] update `waltz.model.logical_flow.LogicalFlow` to be an `ExternalIdProvider`
- [ ] update the `LogicalFlowDao` mappers to read/write the field
- [ ] update the view page to see the external id (if present)

**Comment by TL41** [comment]
for liquibase, see also: https://github.com/finos/waltz/issues/6910 

- prep liquibase version
-- Set by creating a new changelog file ([example](https://github.com/finos/waltz/pull/6911/files#diff-52d0bfc166558485971ebb895e626d6dcc641991b776c7b71831b3a7461fec59)) and referencing it in the master list ([example](https://github.com/finos/waltz/pull/6911/files#diff-5a3bc154a1511b473e081b0d94bf535701e9713791d9b1887630355fb2bf6765))

**Comment by davidwatkins73** [comment]
Merged (again).  Thanks!
