### ISSUE TITLE
Search bar closes on mouseup outside of search box

### ISSUE THREAD

**Issue by JWoodland-Scott** [finos/waltz#6968]
### Description

Need to make sure this only clears if user clicks outside of search box, control by mousedown

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

Search doesn't close unless deliberately clicked outside of search area

### Actual Result

Sometimes search box closes unexpectedly

**Comment by davidwatkins73** [comment]
Switched from a `click` event listener to a `mousedown` event listener.  Tested in Chrome and Firefox
