### ISSUE TITLE
Physical Flow People Involvement: Unable to display People Involvements

### ISSUE THREAD

**Issue by TL41** [finos/waltz#6987]
### Description

It doesn't look like we can display People Involvements on the Physical Flow page. We can add them via the UI, but they do not display.

**We can work on a fix**

---
We think this worked when we added the feature a few releases ago, but it does not look like it works anymore. I didn't do a full trace to see if it recently broke or maybe if there were issues from the start. Either way, it's not working at the moment
https://github.com/finos/waltz/pull/6855

### Waltz Version

1.57

### Steps to Reproduce

1. Add a Person Involvement to a Physical Flow
![01 - physical flow](https://github.com/finos/waltz/assets/59031582/06a826a9-260e-4ed9-b891-1bea86aed371)

2. Check the 'involvement' table to confirm the entry was added
![02 - db](https://github.com/finos/waltz/assets/59031582/603e0b4b-8ae1-4fb8-8441-b66bcb255cf3)

3. Try to add it again and you'll get a message that it may have already been added
![03 - add again to physical flow](https://github.com/finos/waltz/assets/59031582/6239eab3-0523-4b71-9f5e-c0db6e86b059)

4. Refresh the page to view the entry, but it does not display; console shows an error
![04 - view physical flow error](https://github.com/finos/waltz/assets/59031582/712be5c3-4c48-44ca-a9d0-b458f2964427)

### Expected Result

You should be able to view the involvements that were added

### Actual Result

Refresh the page to view the entry, but it does not display; console shows an error

"ServiceBroker::loadData - InvolvementViewService.findAllInvolvementsForEntityByDirection: Server Error - Generic Exception: Cannot determine table fields for entity kind:PHYSICAL_FLOW /"
"Possibly unhandled rejection: {"data":{"message":"Generic Exception: Cannot determine table fields for entity kind:PHYSICAL_FLOW

**Comment by TL41** [comment]
The error message originates in waltz-data/src/main/java/org/finos/waltz/data/JooqUtilities.java

So I think it's just a matter of adding a case for PHYSICAL_FLOW to make the table available, but it will take some dev work and testing

**Comment by davidwatkins73** [comment]
Thanks for the fix!
