### ISSUE TITLE
Request to restart monthly FINOS Waltz project calls 

### ISSUE THREAD

**Issue by mcleo-d** [finos/waltz#7011]
Transferring from https://github.com/finos/community/issues/302 cc @TheJuanAndOnly99 

## Request to restart monthly FINOS Waltz project calls

The NatWest OSPO would like to request a monthly Waltz project call to support the adoption of the project. 

The start date and agenda management can be discussed and agreed once the appetite of FINOS, @davidwatkins73 and @JWoodland-Scott is understood.

Thanks for your consideration.

James.

**Comment by mcleo-d** [comment]
Hello 👋🏻 

Just closing the loop on this thread @maoo and @davidwatkins73.

Let me know if a monthly Waltz call was agreed as it would be good to start inviting the NWG Waltz team to calls.

Speak soon,

James.

**Comment by mcleo-d** [comment]
@davidwatkins73 and @maoo,

I'm very happy with the suggestions made above and have included @TheJuanAndOnly99 to help schedule the Monday meetings and place on the FINOS community calendar.

There is a very active Waltz engineering community at NWG, so I suggest leaning into the UK / IST timezones if engineering is most active in these regions. I suggest meeting at 13:00 BST or before.

I will introduce you to the NWG Waltz maintainers over email so we can align our roadmaps and figure out how NWG can contribute into the upstream project.

James.

**Comment by maoo** [comment]
Thanks @mcleo-d !

@davidwatkins73 - please confirm time and cadence, and we'll setup the meetings and Zoom accesses for you @JWoodland-Scott . TY!

**Comment by davidwatkins73** [comment]
How about the **first Thurs of every month** (starting 2024-05-02).  We do have some interest from some other banks (US based) so not sure how we can balance the timings to cover all timezones (2pm ?)

We propose having each meeting lasting 1hr where the meeting has **3 distinct parts**: 

- new releases and user group q+a
- deep dive on topic (to be advertised in advance, see further below for our starting set of topics)
- contributor topics (coordinating features, notification of larger upcoming work items) 

Initial topics: 

- data flows (incl. classification rules)
  - differences between logical flows, physical flows and specs
  - data types
  - flow participants (apps, actors, eudas)
  - flow classification rules
- taxonomies (ratings, admin)
  -  ...
- assessments
  -  ...
- reporting 
  -  ...
  
Happy to adapt the topics based on community feedback

**Comment by davidwatkins73** [comment]
Possibly shifting the first session back a week or two to accommodate Bank Holidays.  Will post here once the dates and cadence have been confirmed.

**Comment by davidwatkins73** [comment]
Calls have resumed - closing this issue
