### ISSUE TITLE
Measurable Categories: Allow admin to create a new category

### ISSUE THREAD

**Issue by JWoodland-Scott** [finos/waltz#7023]
### Description

Need a feature to create taxonomies through the UI

- [ ] Should have the ability to bulk load the taxonomy for newly created taxonomies 

### Resourcing

We would like to add this request to the Waltz team's feature backlog

**Comment by davidwatkins73** [comment]
Created a new integration test to cover this scenario.
Also discovered that one of the old custom assert methods (`assertChangeLogContainsAtLeastOneMatchingOperation`) was not working correctly - this caused a few (minor) knock on changes / fixes.
