### ISSUE TITLE
Survey Instance: View should make it obvious who to contact

### ISSUE THREAD

**Issue by JWoodland-Scott** [finos/waltz#7030]
### Description

Survey template owner / run owner should be visible

### Resourcing

We intend to contribute this feature

**Comment by davidwatkins73** [comment]
Also sneak this into the section header css:

```
.section-question-header {
    .....
    padding-top: 0.5em;
    padding-bottom: 0.3em;
}
```

**Comment by davidwatkins73** [comment]
<img width="348" alt="image" src="https://github.com/finos/waltz/assets/576829/b1759417-8c91-49a0-9216-04a003e9b45b">
