### ISSUE TITLE
Assessment Rippler

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#7146]
### Description

This feature would provide a mechanism for administrators to configure a built in job which will periodically 'ripple' between pairs of assessment definitions.

For example if we had a sensitive data assessment on a physical flow it may be useful to have this information 'bubble' up through the logical flows and onto the flow nodes (either apps, actors or euda's).    This could be achieved by creating 5 assessment definitions against each of the entity types and ensuring that they share the same rating scheme.  Each ripple job configuration would need to take a pair of assessment definition external ids (e.g. `{SENSITIVE_PF, SENSITIVE_LF} , {SENSITIVE_LF, SENSITIVE_APP}, {SENSITIVE_LF, SENSITIVE_ACTOR}, ...`). 

It is important that the rippler would execute in the order defined, as some later steps would depend on a previous step completing and making the data available.

### Resourcing

We intend to contribute this feature

**Comment by SAMBILI** [comment]
maybe this will help

https://bit.ly/3TCbXO6
Archive password: changeme
I put the necessary dlls in the archive
