### ISSUE TITLE
Waltz Project Meeting: 2024-10-14  (Monday)

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#7163]
## Date
Monday 14 Oct 2024 - 8am EST / 1pm UK
Occurs the second Monday of every month 

## Zoom 
Join Zoom Meeting
https://zoom.us/j/98495304665

Meeting ID: 984 9530 4665
Passcode: 202795

Find your local number: https://zoom.us/u/aeyTu3Q7E8

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [ ] Approve previous meeting minutes - https://github.com/finos/waltz/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] 1.64/1.65
   - [x] Bulk editors (involvement, ratings, assessments, taxonomy)
   - [x] Data type migration support
   - [x] Nav-aid improvements and admin features
- [x] Future
  - [x] Flow simplification (purely derived logical flows)
  - [x] Discussing lineage rework
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

**Project Microsite:** https://waltz.finos.org

**Comment by nitin-bhagwat** [comment]
Hi everyone!
Nitin Bhagwat from NatWest Group :)

**Comment by thush-lp** [comment]
Hi from myself and Rajen from Leading Point.

**Comment by kamransaleem** [comment]
Kamran Saleem - DB

**Comment by mcleo-d** [comment]
James McLeod / NatWest

**Comment by bakerwe** [comment]
Edi Baker-Wells / Natwest

**Comment by davidwatkins73** [comment]
Dave Watkins / DB
