### ISSUE TITLE
Ability to order the capability list by a custom sort index

### ISSUE THREAD

**Issue by mcneilm** [finos/waltz#92]

**Comment by davidwatkins73** [comment]
Model changes:

- [ ] ddl 
  - [ ] ddl doc
- [ ] model
- [ ] dao
- [ ] service ?

Places to change (the ids refer to section identifiers registered in `dynamic-section-definitions`):

- [ ] Measurable Category Page
- [ ] Measurable Page overview (hierarchy widget)
- [ ] Viewpoints section (id: 22)
  - [ ] Overview page
  - [ ] Spindle editor / measurable picker
  - [ ] Spindle viewer / tree mode
- [ ] Survey question
  - [ ] edit
  - [ ] view
- [ ] Ratings section, for apps (id: 15)
  - [ ] view
  - [ ] edit
- [ ] Ratings/roadmap, for vantage (id: 16)
- [ ] Report grid, viewpoint column picker (id: 170)
- [ ] Flow diagram, viewpoint overlay picker 
  - [ ] The list of categories also needs to be sorted
